module mime

pub fn (m Mime) extensions() []string {
	return match m {
		.application_1d_interleaved_parityfec { [] }
		.application_3gpdash_qoe_report_xml { [] }
		.application_3gpp_ims_xml { [] }
		.application_3gpp_mbs_object_manifest_json { [] }
		.application_3gpp_mbs_user_service_descriptions_json { [] }
		.application_3gpp_media_delivery_metrics_report_json { [] }
		.application_3gpp_hal_json { [] }
		.application_3gpp_hal_forms_json { [] }
		.application_aas_zip { [] }
		.application_a2_l { ['a2l'] }
		.application_ace_groupcomm_cbor { [] }
		.application_ace_trl_cbor { [] }
		.application_ace_cbor { [] }
		.application_ace_json { [] }
		.application_activemessage { [] }
		.application_activity_json { ['jsonld'] }
		.application_aif_cbor { [] }
		.application_aif_json { [] }
		.application_alto_cdni_json { [] }
		.application_alto_cdnifilter_json { [] }
		.application_alto_costmap_json { [] }
		.application_alto_costmapfilter_json { [] }
		.application_alto_directory_json { [] }
		.application_alto_endpointprop_json { [] }
		.application_alto_endpointpropparams_json { [] }
		.application_alto_endpointcost_json { [] }
		.application_alto_endpointcostparams_json { [] }
		.application_alto_error_json { [] }
		.application_alto_networkmapfilter_json { [] }
		.application_alto_networkmap_json { [] }
		.application_alto_propmap_json { [] }
		.application_alto_propmapparams_json { [] }
		.application_alto_tips_json { [] }
		.application_alto_tipsparams_json { [] }
		.application_alto_updatestreamcontrol_json { [] }
		.application_alto_updatestreamparams_json { [] }
		.application_aml { ['aml'] }
		.application_andrew_inset { [] }
		.application_applefile { [] }
		.application_asyncapi_json { [] }
		.application_asyncapi_yaml { [] }
		.application_at_jwt { [] }
		.application_atf { ['atf'] }
		.application_atfx { ['atfx'] }
		.application_atom_xml { ['atom'] }
		.application_atomcat_xml { ['atomcat'] }
		.application_atomdeleted_xml { [] }
		.application_atomicmail { [] }
		.application_atomsvc_xml { ['atomsvc'] }
		.application_atsc_dwd_xml { [] }
		.application_atsc_dynamic_event_message { [] }
		.application_atsc_held_xml { [] }
		.application_atsc_rdt_json { [] }
		.application_atsc_rsat_xml { [] }
		.application_atxml { [] }
		.application_auth_policy_xml { [] }
		.application_automationml_aml_xml { [] }
		.application_automationml_amlx_zip { [] }
		.application_bacnet_xdd_zip { [] }
		.application_batch_smtp { [] }
		.application_beep_xml { [] }
		.application_bufr { ['bufr'] }
		.application_c2pa { ['c2pa'] }
		.application_calendar_json { [] }
		.application_calendar_xml { [] }
		.application_call_completion { [] }
		.application_cals_1840 { [] }
		.application_captive_json { [] }
		.application_cbor { ['cbor'] }
		.application_cbor_seq { [] }
		.application_cccex { [] }
		.application_ccmp_xml { [] }
		.application_ccxml_xml { ['ccxml'] }
		.application_cda_xml { ['cda'] }
		.application_cdfx_xml { [] }
		.application_cdmi_capability { ['cdmia'] }
		.application_cdmi_container { ['cdmic'] }
		.application_cdmi_domain { ['cdmid'] }
		.application_cdmi_object { ['cdmio'] }
		.application_cdmi_queue { ['cdmiq'] }
		.application_cdni { [] }
		.application_ce_cbor { [] }
		.application_cea { [] }
		.application_cea_2018_xml { [] }
		.application_cellml_xml { ['cellml', 'xml'] }
		.application_cfw { [] }
		.application_cid { [] }
		.application_cid_edhoc_cbor_seq { [] }
		.application_city_json { [] }
		.application_city_json_seq { [] }
		.application_client_authentication_jwt { [] }
		.application_cloudevents_batch_json { [] }
		.application_cloudevents_json { [] }
		.application_clr { ['clr'] }
		.application_clue_info_xml { [] }
		.application_clue_xml { [] }
		.application_cmcd { [] }
		.application_cms { [] }
		.application_cmw_cbor { [] }
		.application_cmw_cose { [] }
		.application_cmw_json { [] }
		.application_cmw_jws { [] }
		.application_cnrp_xml { [] }
		.application_coap_eap { [] }
		.application_coap_group_json { [] }
		.application_coap_payload { [] }
		.application_commonground { [] }
		.application_concise_problem_details_cbor { [] }
		.application_conference_info_xml { [] }
		.application_cpl_xml { [] }
		.application_cose { ['cose'] }
		.application_cose_key { [] }
		.application_cose_key_set { [] }
		.application_cose_x509 { [] }
		.application_csrattrs { [] }
		.application_csta_xml { [] }
		.application_cst_adata_xml { [] }
		.application_csvm_json { [] }
		.application_cwl { ['cwl'] }
		.application_cwl_json { [] }
		.application_cwl_yaml { [] }
		.application_cwt { ['cwt'] }
		.application_cybercash { [] }
		.application_dash_xml { ['mpd'] }
		.application_dash_patch_xml { [] }
		.application_dashdelta { [] }
		.application_davmount_xml { ['davmount'] }
		.application_dca_rft { [] }
		.application_dcd { [] }
		.application_dec_dx { [] }
		.application_dialog_info_xml { [] }
		.application_dicom { ['dcm'] }
		.application_dicom_json { [] }
		.application_dicom_xml { [] }
		.application_did { [] }
		.application_dii { [] }
		.application_dit { [] }
		.application_dns { [] }
		.application_dns_json { [] }
		.application_dns_message { [] }
		.application_dots_cbor { [] }
		.application_dpop_jwt { [] }
		.application_dskpp_xml { [] }
		.application_dssc_der { ['dssc'] }
		.application_dssc_xml { ['xdssc'] }
		.application_dvcs { [] }
		.application_eat_cwt { [] }
		.application_eat_jwt { [] }
		.application_eat_bun_cbor { [] }
		.application_eat_bun_json { [] }
		.application_eat_ucs_cbor { [] }
		.application_eat_ucs_json { [] }
		.application_ecmascript { ['es', 'ecma'] }
		.application_edhoc_cbor_seq { [] }
		.application_edi_consent { [] }
		.application_edifact { [] }
		.application_edi_x12 { [] }
		.application_efi { ['efi'] }
		.application_elm_json { [] }
		.application_elm_xml { [] }
		.application_emergency_call_data_cap_xml { [] }
		.application_emergency_call_data_comment_xml { [] }
		.application_emergency_call_data_control_xml { [] }
		.application_emergency_call_data_device_info_xml { [] }
		.application_emergency_call_data_e_call_msd { [] }
		.application_emergency_call_data_legacy_esn_json { [] }
		.application_emergency_call_data_provider_info_xml { [] }
		.application_emergency_call_data_service_info_xml { [] }
		.application_emergency_call_data_subscriber_info_xml { [] }
		.application_emergency_call_data_veds_xml { [] }
		.application_emma_xml { ['emma'] }
		.application_emotionml_xml { [] }
		.application_encaprtp { [] }
		.application_entity_statement_jwt { [] }
		.application_epp_xml { [] }
		.application_epub_zip { ['epub'] }
		.application_eshop { [] }
		.application_example { [] }
		.application_exi { ['exi'] }
		.application_expect_ct_report_json { [] }
		.application_explicit_registration_response_jwt { [] }
		.application_express { [] }
		.application_fastinfoset { [] }
		.application_fastsoap { [] }
		.application_fdf { ['fdf'] }
		.application_fdt_xml { [] }
		.application_fhir_json { [] }
		.application_fhir_xml { [] }
		.application_fits { ['fits'] }
		.application_flexfec { [] }
		.application_font_sfnt { [] }
		.application_font_tdpfr { ['pfr'] }
		.application_font_woff { ['woff'] }
		.application_framework_attributes_xml { [] }
		.application_geo_json { ['geojson'] }
		.application_geo_json_seq { [] }
		.application_geofeed_csv { [] }
		.application_geopackage_sqlite3 { ['gpkg'] }
		.application_geopose_json { [] }
		.application_geoxacml_json { [] }
		.application_geoxacml_xml { [] }
		.application_gltf_buffer { ['bin'] }
		.application_gml_xml { ['gml'] }
		.application_gnap_binding_jws { [] }
		.application_gnap_binding_jwsd { [] }
		.application_gnap_binding_rotation_jws { [] }
		.application_gnap_binding_rotation_jwsd { [] }
		.application_grib { ['grib', 'grib2'] }
		.application_gzip { ['gz'] }
		.application_h224 { [] }
		.application_held_xml { [] }
		.application_hl7v2_xml { [] }
		.application_http { [] }
		.application_hyperstudio { ['stk'] }
		.application_ibe_key_request_xml { [] }
		.application_ibe_pkg_reply_xml { [] }
		.application_ibe_pp_data { [] }
		.application_iges { ['igs', 'iges'] }
		.application_im_iscomposing_xml { [] }
		.application_index { [] }
		.application_index_cmd { [] }
		.application_index_obj { [] }
		.application_index_response { [] }
		.application_index_vnd { [] }
		.application_inkml_xml { ['ink', 'inkml'] }
		.application_iotp { [] }
		.application_ipfix { ['ipfix'] }
		.application_ipp { [] }
		.application_isup { [] }
		.application_its_xml { ['its'] }
		.application_java_archive { ['jar', 'war', 'ear'] }
		.application_javascript { ['js', 'mjs'] }
		.application_jf2feed_json { [] }
		.application_jose { [] }
		.application_jose_json { [] }
		.application_jrd_json { [] }
		.application_jscalendar_json { [] }
		.application_jscontact_json { [] }
		.application_json { ['json'] }
		.application_json_patch_json { [] }
		.application_json_patch_query_json { [] }
		.application_json_seq { [] }
		.application_jsonpath { [] }
		.application_jwk_json { [] }
		.application_jwk_set_json { [] }
		.application_jwk_set_jwt { [] }
		.application_jwt { ['jwt'] }
		.application_kb_jwt { [] }
		.application_kbl_xml { [] }
		.application_kpml_request_xml { [] }
		.application_kpml_response_xml { [] }
		.application_ld_json { ['jsonld'] }
		.application_lgr_xml { [] }
		.application_link_format { [] }
		.application_linkset { [] }
		.application_linkset_json { [] }
		.application_load_control_xml { [] }
		.application_logout_jwt { [] }
		.application_lost_xml { ['lostxml'] }
		.application_lostsync_xml { [] }
		.application_lpf_zip { ['lpf'] }
		.application_lxf { [] }
		.application_mac_binhex40 { ['hqx'] }
		.application_macwriteii { [] }
		.application_mads_xml { ['mads'] }
		.application_manifest_json { ['webmanifest'] }
		.application_marc { ['mrc'] }
		.application_marcxml_xml { ['mrcx'] }
		.application_mathematica { ['ma', 'nb', 'mb'] }
		.application_mathml_xml { ['mathml'] }
		.application_mathml_content_xml { [] }
		.application_mathml_presentation_xml { [] }
		.application_mbms_associated_procedure_description_xml { [] }
		.application_mbms_deregister_xml { [] }
		.application_mbms_envelope_xml { [] }
		.application_mbms_msk_response_xml { [] }
		.application_mbms_msk_xml { [] }
		.application_mbms_protection_description_xml { [] }
		.application_mbms_reception_report_xml { [] }
		.application_mbms_register_response_xml { [] }
		.application_mbms_register_xml { [] }
		.application_mbms_schedule_xml { [] }
		.application_mbms_user_service_description_xml { [] }
		.application_mbox { ['mbox'] }
		.application_measured_component_cbor { [] }
		.application_measured_component_json { [] }
		.application_media_control_xml { [] }
		.application_media_policy_dataset_xml { [] }
		.application_mediaservercontrol_xml { ['mscml'] }
		.application_merge_patch_json { [] }
		.application_metalink4_xml { ['meta4'] }
		.application_mets_xml { ['mets'] }
		.application_mf4 { ['mf4'] }
		.application_mikey { [] }
		.application_mipc { [] }
		.application_missing_blocks_cbor_seq { [] }
		.application_mmt_aei_xml { [] }
		.application_mmt_usd_xml { [] }
		.application_mods_xml { ['mods'] }
		.application_moss_keys { [] }
		.application_moss_signature { [] }
		.application_mosskey_data { [] }
		.application_mosskey_request { [] }
		.application_mp21 { ['m21', 'mp21'] }
		.application_mp4 { ['mp4', 'mpg4'] }
		.application_mpeg4_generic { [] }
		.application_mpeg4_iod { [] }
		.application_mpeg4_iod_xmt { [] }
		.application_mrb_consumer_xml { [] }
		.application_mrb_publish_xml { [] }
		.application_msc_ivr_xml { [] }
		.application_msc_mixer_xml { [] }
		.application_msword { ['doc', 'dot'] }
		.application_mud_json { ['mud'] }
		.application_multipart_core { [] }
		.application_mxf { ['mxf'] }
		.application_n_quads { ['nq'] }
		.application_n_triples { ['nt'] }
		.application_nasdata { [] }
		.application_news_checkgroups { [] }
		.application_news_groupinfo { [] }
		.application_news_transmission { [] }
		.application_nlsml_xml { [] }
		.application_node { ['cjs'] }
		.application_nss { [] }
		.application_oauth_authz_req_jwt { [] }
		.application_oblivious_dns_message { [] }
		.application_ocsp_request { [] }
		.application_ocsp_response { [] }
		.application_octet_stream { ['bin', 'dms', 'lrf', 'mar', 'so', 'dist', 'distz', 'pkg', 'bpk', 'dump', 'elc', 'deploy', 'exe', 'dll', 'deb', 'dmg', 'iso', 'img', 'msi', 'msp', 'msm', 'buffer'] }
		.application_oda { ['oda'] }
		.application_odm_xml { [] }
		.application_odx { ['odx'] }
		.application_oebps_package_xml { ['opf'] }
		.application_ogg { ['ogx'] }
		.application_ohttp_keys { [] }
		.application_opc_nodeset_xml { [] }
		.application_oscore { [] }
		.application_oxps { ['oxps'] }
		.application_p21 { ['p21'] }
		.application_p21_zip { [] }
		.application_p2p_overlay_xml { ['relo'] }
		.application_parityfec { [] }
		.application_passport { [] }
		.application_patch_ops_error_xml { ['xer'] }
		.application_pdf { ['pdf'] }
		.application_pdx { ['pdx'] }
		.application_pem_certificate_chain { [] }
		.application_pgp_encrypted { ['pgp'] }
		.application_pgp_keys { ['asc'] }
		.application_pgp_signature { ['asc', 'sig'] }
		.application_pidf_diff_xml { [] }
		.application_pidf_xml { [] }
		.application_pkcs10 { ['p10'] }
		.application_pkcs7_mime { ['p7m', 'p7c'] }
		.application_pkcs7_signature { ['p7s'] }
		.application_pkcs8 { ['p8'] }
		.application_pkcs8_encrypted { [] }
		.application_pkcs12 { ['p12', 'pfx'] }
		.application_pkix_attr_cert { ['ac'] }
		.application_pkix_cert { ['cer'] }
		.application_pkix_crl { ['crl'] }
		.application_pkix_pkipath { ['pkipath'] }
		.application_pkixcmp { ['pki'] }
		.application_pls_xml { ['pls'] }
		.application_poc_settings_xml { [] }
		.application_postscript { ['ai', 'eps', 'ps'] }
		.application_ppsp_tracker_json { [] }
		.application_private_token_issuer_directory { [] }
		.application_private_token_request { [] }
		.application_private_token_response { [] }
		.application_problem_json { [] }
		.application_problem_xml { [] }
		.application_protobuf { ['pb', 'proto'] }
		.application_protobuf_json { [] }
		.application_provenance_xml { ['provx'] }
		.application_provided_claims_jwt { [] }
		.application_prs_alvestrand_titrax_sheet { [] }
		.application_prs_bwtc32key { [] }
		.application_prs_cww { ['cww'] }
		.application_prs_cyn { [] }
		.application_prs_hpub_zip { [] }
		.application_prs_implied_document_xml { [] }
		.application_prs_implied_executable { [] }
		.application_prs_implied_object_json { [] }
		.application_prs_implied_object_json_seq { [] }
		.application_prs_implied_object_yaml { [] }
		.application_prs_implied_structure { [] }
		.application_prs_mayfile { [] }
		.application_prs_nprend { ['rnd', 'rct'] }
		.application_prs_plucker { [] }
		.application_prs_rdf_xml_crypt { [] }
		.application_prs_sclt { [] }
		.application_prs_vcfbzip2 { [] }
		.application_prs_xsf_xml { [] }
		.application_pskc_xml { ['pskcxml'] }
		.application_pvd_json { [] }
		.application_rdf_xml { ['rdf', 'owl'] }
		.application_roughtime_malfeasance_json { [] }
		.application_roughtime_server_json { [] }
		.application_route_apd_xml { [] }
		.application_route_s_tsid_xml { [] }
		.application_route_usd_xml { [] }
		.application_qsig { [] }
		.application_raptorfec { [] }
		.application_rdap_json { [] }
		.application_reginfo_xml { ['rif'] }
		.application_relax_ng_compact_syntax { ['rnc'] }
		.application_remote_printing { [] }
		.application_reputon_json { [] }
		.application_resolve_response_jwt { [] }
		.application_resource_lists_diff_xml { ['rld'] }
		.application_resource_lists_xml { ['rl'] }
		.application_rfc_xml { ['rfcxml'] }
		.application_riscos { [] }
		.application_rlmi_xml { [] }
		.application_rls_services_xml { ['rs'] }
		.application_rpki_checklist { [] }
		.application_rpki_ghostbusters { ['gbr'] }
		.application_rpki_manifest { ['mft'] }
		.application_rpki_publication { [] }
		.application_rpki_roa { ['roa'] }
		.application_rpki_signed_tal { [] }
		.application_rpki_updown { [] }
		.application_rs_metadata_xml { [] }
		.application_rtf { ['rtf'] }
		.application_rtploopback { [] }
		.application_rtx { [] }
		.application_samlassertion_xml { [] }
		.application_samlmetadata_xml { ['md'] }
		.application_sarif_external_properties_json { ['sarif-external-properties'] }
		.application_sarif_json { ['sarif'] }
		.application_sbe { [] }
		.application_sbml_xml { ['sbml'] }
		.application_scaip_xml { [] }
		.application_scim_json { [] }
		.application_scitt_receipt_cose { [] }
		.application_scitt_statement_cose { [] }
		.application_scvp_cv_request { ['scq'] }
		.application_scvp_cv_response { ['scs'] }
		.application_scvp_vp_request { ['spq'] }
		.application_scvp_vp_response { ['spp'] }
		.application_sd_jwt { [] }
		.application_sd_jwt_json { [] }
		.application_sdf_json { ['sdf'] }
		.application_sdp { ['sdp'] }
		.application_secevent_jwt { [] }
		.application_senml_etch_cbor { [] }
		.application_senml_etch_json { [] }
		.application_senml_exi { ['senml-exi'] }
		.application_senml_cbor { ['senmlc'] }
		.application_senml_json { ['senml'] }
		.application_senml_xml { ['senmlx'] }
		.application_sensml_exi { ['sensml-exi'] }
		.application_sensml_cbor { ['sensmlc'] }
		.application_sensml_json { ['sensml'] }
		.application_sensml_xml { ['sensmlx'] }
		.application_sep_exi { [] }
		.application_sep_xml { [] }
		.application_session_info { [] }
		.application_set_payment { [] }
		.application_set_payment_initiation { [] }
		.application_set_registration { [] }
		.application_set_registration_initiation { [] }
		.application_sgml { [] }
		.application_sgml_open_catalog { [] }
		.application_shf_xml { ['shf'] }
		.application_sieve { ['siv', 'sieve'] }
		.application_simple_filter_xml { ['cl'] }
		.application_simple_message_summary { [] }
		.application_simple_symbol_container { [] }
		.application_sipc { [] }
		.application_slate { [] }
		.application_smil { ['smi', 'smil'] }
		.application_smil_xml { ['smi', 'smil'] }
		.application_smpte336m { [] }
		.application_soap_fastinfoset { [] }
		.application_soap_xml { [] }
		.application_sparql_query { ['rq'] }
		.application_spdx_json { ['spdx'] }
		.application_sparql_results_xml { ['srx'] }
		.application_spirits_event_xml { [] }
		.application_sql { ['sql'] }
		.application_srgs { ['gram'] }
		.application_srgs_xml { ['grxml'] }
		.application_sru_xml { ['sru'] }
		.application_sslkeylogfile { [] }
		.application_ssml_xml { ['ssml'] }
		.application_st2110_41 { [] }
		.application_stix_json { [] }
		.application_stratum { [] }
		.application_suit_envelope_cose { [] }
		.application_suit_report_cose { [] }
		.application_swid_cbor { [] }
		.application_swid_xml { ['swidtag'] }
		.application_syslog_msg { [] }
		.application_tamp_apex_update { [] }
		.application_tamp_apex_update_confirm { [] }
		.application_tamp_community_update { [] }
		.application_tamp_community_update_confirm { [] }
		.application_tamp_error { [] }
		.application_tamp_sequence_adjust { [] }
		.application_tamp_sequence_adjust_confirm { [] }
		.application_tamp_status_query { [] }
		.application_tamp_status_response { [] }
		.application_tamp_update { [] }
		.application_tamp_update_confirm { [] }
		.application_taxii_json { [] }
		.application_td_json { [] }
		.application_teep_cbor { [] }
		.application_tei_xml { ['tei', 'teicorpus'] }
		.application_tetra_isi { [] }
		.application_texinfo { ['texinfo', 'texi'] }
		.application_thraud_xml { ['tfi'] }
		.application_timestamp_query { ['tsq'] }
		.application_timestamp_reply { ['tsr'] }
		.application_timestamped_data { ['tsd'] }
		.application_tlsrpt_gzip { [] }
		.application_tlsrpt_json { [] }
		.application_tm_json { [] }
		.application_tnauthlist { [] }
		.application_toc_cbor { [] }
		.application_token_introspection_jwt { [] }
		.application_toml { ['toml'] }
		.application_trickle_ice_sdpfrag { [] }
		.application_trig { ['trig'] }
		.application_trust_chain_json { [] }
		.application_trust_mark_jwt { [] }
		.application_trust_mark_delegation_jwt { [] }
		.application_trust_mark_status_response_jwt { [] }
		.application_ttml_xml { ['ttml'] }
		.application_tve_trigger { [] }
		.application_tzif { [] }
		.application_tzif_leap { [] }
		.application_uccs_cbor { [] }
		.application_ujcs_json { [] }
		.application_ulpfec { [] }
		.application_urc_grpsheet_xml { [] }
		.application_urc_ressheet_xml { ['rsheet'] }
		.application_urc_targetdesc_xml { ['td'] }
		.application_urc_uisocketdesc_xml { [] }
		.application_v3c { ['v3c'] }
		.application_vc { [] }
		.application_vc_cose { [] }
		.application_vc_jwt { [] }
		.application_vc_sd_jwt { [] }
		.application_vcard_json { [] }
		.application_vcard_xml { [] }
		.application_vec_xml { [] }
		.application_vec_package_gzip { [] }
		.application_vec_package_zip { [] }
		.application_vemmi { [] }
		.application_vnd_1000minds_decision_model_xml { [] }
		.application_vnd_1ob { [] }
		.application_vnd_3gpp_5gnas { [] }
		.application_vnd_3gpp_5gsa2x { [] }
		.application_vnd_3gpp_5gsa2x_local_service_information { [] }
		.application_vnd_3gpp_5gsv2x { [] }
		.application_vnd_3gpp_5gsv2x_local_service_information { [] }
		.application_vnd_3gpp_access_transfer_events_xml { [] }
		.application_vnd_3gpp_bsf_xml { [] }
		.application_vnd_3gpp_crs_xml { [] }
		.application_vnd_3gpp_current_location_discovery_xml { [] }
		.application_vnd_3gpp_gmop_xml { [] }
		.application_vnd_3gpp_gtpc { [] }
		.application_vnd_3gpp_interworking_data { [] }
		.application_vnd_3gpp_lpp { [] }
		.application_vnd_3gpp_mc_signalling_ear { [] }
		.application_vnd_3gpp_mcdata_affiliation_command_xml { [] }
		.application_vnd_3gpp_mcdata_info_xml { [] }
		.application_vnd_3gpp_mcdata_msgstore_ctrl_request_xml { [] }
		.application_vnd_3gpp_mcdata_payload { [] }
		.application_vnd_3gpp_mcdata_regroup_xml { [] }
		.application_vnd_3gpp_mcdata_service_config_xml { [] }
		.application_vnd_3gpp_mcdata_signalling { [] }
		.application_vnd_3gpp_mcdata_ue_config_xml { [] }
		.application_vnd_3gpp_mcdata_user_profile_xml { [] }
		.application_vnd_3gpp_mcptt_affiliation_command_xml { [] }
		.application_vnd_3gpp_mcptt_floor_request_xml { [] }
		.application_vnd_3gpp_mcptt_info_xml { [] }
		.application_vnd_3gpp_mcptt_location_info_xml { [] }
		.application_vnd_3gpp_mcptt_mbms_usage_info_xml { [] }
		.application_vnd_3gpp_mcptt_regroup_xml { [] }
		.application_vnd_3gpp_mcptt_service_config_xml { [] }
		.application_vnd_3gpp_mcptt_signed_xml { [] }
		.application_vnd_3gpp_mcptt_ue_config_xml { [] }
		.application_vnd_3gpp_mcptt_ue_init_config_xml { [] }
		.application_vnd_3gpp_mcptt_user_profile_xml { [] }
		.application_vnd_3gpp_mcs_location_user_config_xml { [] }
		.application_vnd_3gpp_mcvideo_affiliation_command_xml { [] }
		.application_vnd_3gpp_mcvideo_affiliation_info_xml { [] }
		.application_vnd_3gpp_mcvideo_info_xml { [] }
		.application_vnd_3gpp_mcvideo_location_info_xml { [] }
		.application_vnd_3gpp_mcvideo_mbms_usage_info_xml { [] }
		.application_vnd_3gpp_mcvideo_regroup_xml { [] }
		.application_vnd_3gpp_mcvideo_service_config_xml { [] }
		.application_vnd_3gpp_mcvideo_transmission_request_xml { [] }
		.application_vnd_3gpp_mcvideo_ue_config_xml { [] }
		.application_vnd_3gpp_mcvideo_user_profile_xml { [] }
		.application_vnd_3gpp_mid_call_xml { [] }
		.application_vnd_3gpp_ngap { [] }
		.application_vnd_3gpp_pfcp { [] }
		.application_vnd_3gpp_pic_bw_large { ['plb'] }
		.application_vnd_3gpp_pic_bw_small { ['psb'] }
		.application_vnd_3gpp_pic_bw_var { ['pvb'] }
		.application_vnd_3gpp_pinapp_info_xml { [] }
		.application_vnd_3gpp_prose_pc3a_xml { [] }
		.application_vnd_3gpp_prose_pc3ach_xml { [] }
		.application_vnd_3gpp_prose_pc3ch_xml { [] }
		.application_vnd_3gpp_prose_pc8_xml { [] }
		.application_vnd_3gpp_prose_xml { [] }
		.application_vnd_3gpp_s1ap { [] }
		.application_vnd_3gpp_seal_app_comm_requirements_info_xml { [] }
		.application_vnd_3gpp_seal_data_delivery_info_cbor { [] }
		.application_vnd_3gpp_seal_data_delivery_info_xml { [] }
		.application_vnd_3gpp_seal_group_doc_xml { [] }
		.application_vnd_3gpp_seal_info_xml { [] }
		.application_vnd_3gpp_seal_location_info_cbor { [] }
		.application_vnd_3gpp_seal_location_info_xml { [] }
		.application_vnd_3gpp_seal_mbms_usage_info_xml { [] }
		.application_vnd_3gpp_seal_mbs_usage_info_xml { [] }
		.application_vnd_3gpp_seal_network_qo_s_management_info_xml { [] }
		.application_vnd_3gpp_seal_network_resource_info_cbor { [] }
		.application_vnd_3gpp_seal_ue_config_info_xml { [] }
		.application_vnd_3gpp_seal_unicast_info_xml { [] }
		.application_vnd_3gpp_seal_user_profile_info_xml { [] }
		.application_vnd_3gpp_sms { [] }
		.application_vnd_3gpp_sms_xml { [] }
		.application_vnd_3gpp_srvcc_ext_xml { [] }
		.application_vnd_3gpp_srvcc_info_xml { [] }
		.application_vnd_3gpp_state_and_event_info_xml { [] }
		.application_vnd_3gpp_ussd_xml { [] }
		.application_vnd_3gpp_vae_info_xml { [] }
		.application_vnd_3gpp_v2x_local_service_information { [] }
		.application_vnd_3gpp2_bcmcsinfo_xml { [] }
		.application_vnd_3gpp2_sms { [] }
		.application_vnd_3gpp2_tcap { ['tcap'] }
		.application_vnd_3gpp_v2x { [] }
		.application_vnd_3lightssoftware_imagescal { ['imgcal'] }
		.application_vnd_3_m_post_it_notes { ['pwn'] }
		.application_vnd_accpac_simply_aso { ['aso'] }
		.application_vnd_accpac_simply_imp { ['imp'] }
		.application_vnd_acm_addressxfer_json { [] }
		.application_vnd_acm_chatbot_json { [] }
		.application_vnd_acucobol { ['acu'] }
		.application_vnd_acucorp { ['atc', 'acutc'] }
		.application_vnd_adobe_flash_movie { ['swf'] }
		.application_vnd_adobe_formscentral_fcdt { ['fcdt'] }
		.application_vnd_adobe_fxp { ['fxp', 'fxpl'] }
		.application_vnd_adobe_partial_upload { [] }
		.application_vnd_adobe_xdp_xml { ['xdp'] }
		.application_vnd_aether_imp { [] }
		.application_vnd_afpc_afplinedata { [] }
		.application_vnd_afpc_afplinedata_pagedef { [] }
		.application_vnd_afpc_cmoca_cmresource { [] }
		.application_vnd_afpc_foca_charset { [] }
		.application_vnd_afpc_foca_codedfont { [] }
		.application_vnd_afpc_foca_codepage { [] }
		.application_vnd_afpc_modca { [] }
		.application_vnd_afpc_modca_cmtable { [] }
		.application_vnd_afpc_modca_formdef { [] }
		.application_vnd_afpc_modca_mediummap { [] }
		.application_vnd_afpc_modca_objectcontainer { [] }
		.application_vnd_afpc_modca_overlay { [] }
		.application_vnd_afpc_modca_pagesegment { [] }
		.application_vnd_age { ['age'] }
		.application_vnd_ah_barcode { [] }
		.application_vnd_ahead_space { ['ahead'] }
		.application_vnd_aia { [] }
		.application_vnd_airzip_filesecure_azf { ['azf'] }
		.application_vnd_airzip_filesecure_azs { ['azs'] }
		.application_vnd_amadeus_json { [] }
		.application_vnd_amazon_mobi8_ebook { ['azw3'] }
		.application_vnd_americandynamics_acc { ['acc'] }
		.application_vnd_amiga_ami { ['ami'] }
		.application_vnd_amundsen_maze_xml { [] }
		.application_vnd_android_ota { [] }
		.application_vnd_anki { [] }
		.application_vnd_anser_web_certificate_issue_initiation { ['cii'] }
		.application_vnd_antix_game_component { ['atx'] }
		.application_vnd_apache_arrow_file { ['arrow'] }
		.application_vnd_apache_arrow_stream { [] }
		.application_vnd_apache_parquet { ['parquet'] }
		.application_vnd_apache_thrift_binary { [] }
		.application_vnd_apache_thrift_compact { [] }
		.application_vnd_apache_thrift_json { [] }
		.application_vnd_apexlang { [] }
		.application_vnd_api_json { [] }
		.application_vnd_aplextor_warrp_json { [] }
		.application_vnd_apothekende_reservation_json { [] }
		.application_vnd_apple_installer_xml { ['mpkg'] }
		.application_vnd_apple_keynote { ['key'] }
		.application_vnd_apple_mpegurl { ['m3u8'] }
		.application_vnd_apple_numbers { ['numbers'] }
		.application_vnd_apple_pages { ['pages'] }
		.application_vnd_arastra_swi { [] }
		.application_vnd_aristanetworks_swi { ['swi'] }
		.application_vnd_artisan_json { [] }
		.application_vnd_artsquare { [] }
		.application_vnd_as207960_vas_config_jer { [] }
		.application_vnd_as207960_vas_config_uper { [] }
		.application_vnd_as207960_vas_tap_jer { [] }
		.application_vnd_as207960_vas_tap_uper { [] }
		.application_vnd_astraea_software_iota { ['iota'] }
		.application_vnd_audiograph { ['aep'] }
		.application_vnd_autopackage { [] }
		.application_vnd_avalon_json { [] }
		.application_vnd_avistar_xml { [] }
		.application_vnd_balsamiq_bmml_xml { ['bmml'] }
		.application_vnd_banana_accounting { ['ac'] }
		.application_vnd_bbf_usp_error { [] }
		.application_vnd_bbf_usp_msg { [] }
		.application_vnd_bbf_usp_msg_json { [] }
		.application_vnd_balsamiq_bmpr { ['bmpr'] }
		.application_vnd_bekitzur_stech_json { [] }
		.application_vnd_belightsoft_lhzd_zip { [] }
		.application_vnd_belightsoft_lhzl_zip { [] }
		.application_vnd_bint_med_content { [] }
		.application_vnd_biopax_rdf_xml { [] }
		.application_vnd_blink_idb_value_wrapper { [] }
		.application_vnd_blueice_multipass { ['mpm'] }
		.application_vnd_bluetooth_ep_oob { [] }
		.application_vnd_bluetooth_le_oob { [] }
		.application_vnd_bmi { ['bmi'] }
		.application_vnd_bpf { [] }
		.application_vnd_bpf3 { [] }
		.application_vnd_businessobjects { ['rep'] }
		.application_vnd_byu_uapi_json { [] }
		.application_vnd_bzip3 { ['bz3'] }
		.application_vnd_c3voc_schedule_xml { [] }
		.application_vnd_cab_jscript { [] }
		.application_vnd_canon_cpdl { [] }
		.application_vnd_canon_lips { [] }
		.application_vnd_capasystems_pg_json { [] }
		.application_vnd_cel { [] }
		.application_vnd_cendio_thinlinc_clientconf { [] }
		.application_vnd_century_systems_tcp_stream { [] }
		.application_vnd_chemdraw_xml { ['cdxml'] }
		.application_vnd_chess_pgn { ['pgn'] }
		.application_vnd_chipnuts_karaoke_mmd { ['mmd'] }
		.application_vnd_ciedi { [] }
		.application_vnd_cinderella { ['cdy'] }
		.application_vnd_cirpack_isdn_ext { [] }
		.application_vnd_citationstyles_style_xml { ['csl'] }
		.application_vnd_claymore { ['cla'] }
		.application_vnd_cloanto_rp9 { ['rp9'] }
		.application_vnd_clonk_c4group { ['c4g', 'c4d', 'c4f', 'c4p', 'c4u'] }
		.application_vnd_cluetrust_cartomobile_config { ['c11amc'] }
		.application_vnd_cluetrust_cartomobile_config_pkg { ['c11amz'] }
		.application_vnd_cmmf_configuration_information_json { [] }
		.application_vnd_cmmf_efd_xml { [] }
		.application_vnd_cmmf_encoder_configuration_json { [] }
		.application_vnd_cncf_helm_chart_content_v1_tar_gzip { [] }
		.application_vnd_cncf_helm_chart_provenance_v1_prov { [] }
		.application_vnd_cncf_helm_config_v1_json { [] }
		.application_vnd_coffeescript { [] }
		.application_vnd_collabio_xodocuments_document { [] }
		.application_vnd_collabio_xodocuments_document_template { [] }
		.application_vnd_collabio_xodocuments_presentation { [] }
		.application_vnd_collabio_xodocuments_presentation_template { [] }
		.application_vnd_collabio_xodocuments_spreadsheet { [] }
		.application_vnd_collabio_xodocuments_spreadsheet_template { [] }
		.application_vnd_collection_doc_json { [] }
		.application_vnd_collection_json { [] }
		.application_vnd_collection_next_json { [] }
		.application_vnd_comicbook_rar { ['cbr'] }
		.application_vnd_comicbook_zip { ['cbz'] }
		.application_vnd_commerce_battelle { [] }
		.application_vnd_commonspace { ['csp'] }
		.application_vnd_coreos_ignition_json { [] }
		.application_vnd_cosmocaller { ['cmc'] }
		.application_vnd_contact_cmsg { ['cdbcmsg'] }
		.application_vnd_crick_clicker { ['clkx'] }
		.application_vnd_crick_clicker_keyboard { ['clkk'] }
		.application_vnd_crick_clicker_palette { ['clkp'] }
		.application_vnd_crick_clicker_template { ['clkt'] }
		.application_vnd_crick_clicker_wordbank { ['clkw'] }
		.application_vnd_criticaltools_wbs_xml { ['wbs'] }
		.application_vnd_cryptii_pipe_json { [] }
		.application_vnd_crypto_shade_file { [] }
		.application_vnd_cryptomator_encrypted { [] }
		.application_vnd_cryptomator_vault { [] }
		.application_vnd_ctc_posml { ['pml'] }
		.application_vnd_ctct_ws_xml { [] }
		.application_vnd_cups_pdf { [] }
		.application_vnd_cups_postscript { [] }
		.application_vnd_cups_ppd { ['ppd'] }
		.application_vnd_cups_raster { [] }
		.application_vnd_cups_raw { [] }
		.application_vnd_curl { ['curl'] }
		.application_vnd_cyan_dean_root_xml { [] }
		.application_vnd_cybank { [] }
		.application_vnd_cyclonedx_json { [] }
		.application_vnd_cyclonedx_xml { [] }
		.application_vnd_d2l_coursepackage1p0_zip { [] }
		.application_vnd_d3m_dataset { [] }
		.application_vnd_d3m_problem { [] }
		.application_vnd_dart { ['dart'] }
		.application_vnd_data_vision_rdz { ['rdz'] }
		.application_vnd_datalog { [] }
		.application_vnd_datapackage_json { [] }
		.application_vnd_dataresource_json { [] }
		.application_vnd_dbf { ['dbf'] }
		.application_vnd_dcmp_xml { [] }
		.application_vnd_debian_binary_package { ['deb', 'udeb'] }
		.application_vnd_dece_data { ['uvf', 'uvvf', 'uvd', 'uvvd'] }
		.application_vnd_dece_ttml_xml { ['uvt', 'uvvt'] }
		.application_vnd_dece_unspecified { ['uvx', 'uvvx'] }
		.application_vnd_dece_zip { ['uvz', 'uvvz'] }
		.application_vnd_denovo_fcselayout_link { ['fe_launch'] }
		.application_vnd_desmume_movie { ['dsm'] }
		.application_vnd_deut_json { [] }
		.application_vnd_digitalstack_document_zip { [] }
		.application_vnd_dir_bi_plate_dl_nosuffix { [] }
		.application_vnd_dm_delegation_xml { [] }
		.application_vnd_dna { ['dna'] }
		.application_vnd_document_json { [] }
		.application_vnd_dolby_mobile_1 { [] }
		.application_vnd_dolby_mobile_2 { [] }
		.application_vnd_doremir_scorecloud_binary_document { ['scld'] }
		.application_vnd_dpgraph { ['dpg'] }
		.application_vnd_dreamfactory { ['dfac'] }
		.application_vnd_drive_json { [] }
		.application_vnd_dtg_local { [] }
		.application_vnd_dtg_local_flash { [] }
		.application_vnd_dtg_local_html { [] }
		.application_vnd_dvb_ait { ['ait'] }
		.application_vnd_dvb_dvbisl_xml { [] }
		.application_vnd_dvb_dvbj { ['dvbj'] }
		.application_vnd_dvb_esgcontainer { [] }
		.application_vnd_dvb_ipdcdftnotifaccess { [] }
		.application_vnd_dvb_ipdcesgaccess { [] }
		.application_vnd_dvb_ipdcesgaccess2 { [] }
		.application_vnd_dvb_ipdcesgpdd { [] }
		.application_vnd_dvb_ipdcroaming { [] }
		.application_vnd_dvb_iptv_alfec_base { [] }
		.application_vnd_dvb_iptv_alfec_enhancement { [] }
		.application_vnd_dvb_notif_aggregate_root_xml { [] }
		.application_vnd_dvb_notif_container_xml { [] }
		.application_vnd_dvb_notif_generic_xml { [] }
		.application_vnd_dvb_notif_ia_msglist_xml { [] }
		.application_vnd_dvb_notif_ia_registration_request_xml { [] }
		.application_vnd_dvb_notif_ia_registration_response_xml { [] }
		.application_vnd_dvb_notif_init_xml { [] }
		.application_vnd_dvb_pfr { [] }
		.application_vnd_dvb_service { ['svc'] }
		.application_vnd_dxr { [] }
		.application_vnd_dynageo { ['geo'] }
		.application_vnd_dzr { [] }
		.application_vnd_easykaraoke_cdgdownload { [] }
		.application_vnd_ecip_rlp { [] }
		.application_vnd_edulith_edux_json { [] }
		.application_vnd_ecdis_update { [] }
		.application_vnd_eclipse_ditto_json { [] }
		.application_vnd_ecowin_chart { ['mag'] }
		.application_vnd_ecowin_filerequest { [] }
		.application_vnd_ecowin_fileupdate { [] }
		.application_vnd_ecowin_series { [] }
		.application_vnd_ecowin_seriesrequest { [] }
		.application_vnd_ecowin_seriesupdate { [] }
		.application_vnd_efi_img { ['img'] }
		.application_vnd_efi_iso { ['iso'] }
		.application_vnd_eln_zip { [] }
		.application_vnd_emclient_accessrequest_xml { [] }
		.application_vnd_enliven { ['nml'] }
		.application_vnd_enphase_envoy { [] }
		.application_vnd_eprints_data_xml { [] }
		.application_vnd_epson_esf { ['esf'] }
		.application_vnd_epson_msf { ['msf'] }
		.application_vnd_epson_quickanime { ['qam'] }
		.application_vnd_epson_salt { ['slt'] }
		.application_vnd_epson_ssf { ['ssf'] }
		.application_vnd_ericsson_quickcall { [] }
		.application_vnd_erofs { [] }
		.application_vnd_espass_espass_zip { [] }
		.application_vnd_eszigno3_xml { ['es3', 'et3'] }
		.application_vnd_etsi_aoc_xml { [] }
		.application_vnd_etsi_asic_s_zip { [] }
		.application_vnd_etsi_asic_e_zip { [] }
		.application_vnd_etsi_cug_xml { [] }
		.application_vnd_etsi_iptvcommand_xml { [] }
		.application_vnd_etsi_iptvdiscovery_xml { [] }
		.application_vnd_etsi_iptvprofile_xml { [] }
		.application_vnd_etsi_iptvsad_bc_xml { [] }
		.application_vnd_etsi_iptvsad_cod_xml { [] }
		.application_vnd_etsi_iptvsad_npvr_xml { [] }
		.application_vnd_etsi_iptvservice_xml { [] }
		.application_vnd_etsi_iptvsync_xml { [] }
		.application_vnd_etsi_iptvueprofile_xml { [] }
		.application_vnd_etsi_mcid_xml { [] }
		.application_vnd_etsi_mheg5 { [] }
		.application_vnd_etsi_overload_control_policy_dataset_xml { [] }
		.application_vnd_etsi_pstn_xml { [] }
		.application_vnd_etsi_sci_xml { [] }
		.application_vnd_etsi_simservs_xml { [] }
		.application_vnd_etsi_timestamp_token { [] }
		.application_vnd_etsi_tsl_xml { [] }
		.application_vnd_etsi_tsl_der { [] }
		.application_vnd_eu_kasparian_car_json { [] }
		.application_vnd_eudora_data { [] }
		.application_vnd_evolv_ecig_profile { [] }
		.application_vnd_evolv_ecig_settings { [] }
		.application_vnd_evolv_ecig_theme { [] }
		.application_vnd_exstream_empower_zip { [] }
		.application_vnd_exstream_package { [] }
		.application_vnd_ezpix_album { ['ez2'] }
		.application_vnd_ezpix_package { ['ez3'] }
		.application_vnd_f_secure_mobile { ['fsc'] }
		.application_vnd_faf_yaml { [] }
		.application_vnd_fastcopy_disk_image { [] }
		.application_vnd_familysearch_gedcom_zip { [] }
		.application_vnd_fdsn_mseed { ['mseed'] }
		.application_vnd_fdsn_seed { ['seed', 'dataless'] }
		.application_vnd_fdsn_stationxml_xml { [] }
		.application_vnd_ffsns { [] }
		.application_vnd_fgb { [] }
		.application_vnd_ficlab_flb_zip { [] }
		.application_vnd_filmit_zfc { [] }
		.application_vnd_fints { [] }
		.application_vnd_firemonkeys_cloudcell { [] }
		.application_vnd_flo_graph_it { ['gph'] }
		.application_vnd_fluxtime_clip { ['ftc'] }
		.application_vnd_font_fontforge_sfd { [] }
		.application_vnd_foritech_container { [] }
		.application_vnd_framemaker { ['fm', 'frame', 'maker', 'book'] }
		.application_vnd_freelog_comic { [] }
		.application_vnd_frogans_fnc { ['fnc'] }
		.application_vnd_frogans_ltf { ['ltf'] }
		.application_vnd_fsc_weblaunch { ['fsc'] }
		.application_vnd_fujifilm_fb_docuworks { ['fzs'] }
		.application_vnd_fujifilm_fb_docuworks_binder { [] }
		.application_vnd_fujifilm_fb_docuworks_container { [] }
		.application_vnd_fujifilm_fb_jfi_xml { [] }
		.application_vnd_fujitsu_oasys { ['oas'] }
		.application_vnd_fujitsu_oasys2 { ['oa2'] }
		.application_vnd_fujitsu_oasys3 { ['oa3'] }
		.application_vnd_fujitsu_oasysgp { ['fg5'] }
		.application_vnd_fujitsu_oasysprs { ['bh2'] }
		.application_vnd_fujixerox_art4 { [] }
		.application_vnd_fujixerox_art_ex { [] }
		.application_vnd_fujixerox_ddd { ['ddd'] }
		.application_vnd_fujixerox_docuworks { ['xdw'] }
		.application_vnd_fujixerox_docuworks_binder { ['xbd'] }
		.application_vnd_fujixerox_docuworks_container { [] }
		.application_vnd_fujixerox_hbpl { [] }
		.application_vnd_fut_misnet { [] }
		.application_vnd_futoin_cbor { [] }
		.application_vnd_futoin_json { [] }
		.application_vnd_fuzzysheet { ['fzs'] }
		.application_vnd_g3pix_g3fc { [] }
		.application_vnd_ga4gh_passport_jwt { [] }
		.application_vnd_genomatix_tuxedo { ['txd'] }
		.application_vnd_genozip { ['genozip'] }
		.application_vnd_gentics_grd_json { [] }
		.application_vnd_gentoo_catmetadata_xml { [] }
		.application_vnd_gentoo_ebuild { ['ebuild'] }
		.application_vnd_gentoo_eclass { ['eclass'] }
		.application_vnd_gentoo_gpkg { [] }
		.application_vnd_gentoo_manifest { [] }
		.application_vnd_gentoo_xpak { [] }
		.application_vnd_gentoo_pkgmetadata_xml { [] }
		.application_vnd_geo_json { ['geojson'] }
		.application_vnd_geocube_xml { [] }
		.application_vnd_geogebra_file { ['ggb'] }
		.application_vnd_geogebra_pinboard { [] }
		.application_vnd_geogebra_slides { [] }
		.application_vnd_geogebra_tool { ['ggt'] }
		.application_vnd_geometry_explorer { ['gex', 'gre'] }
		.application_vnd_geonext { ['gxt'] }
		.application_vnd_geoplan { ['g2w'] }
		.application_vnd_geospace { ['g3w'] }
		.application_vnd_gerber { [] }
		.application_vnd_globalplatform_card_content_mgt { [] }
		.application_vnd_globalplatform_card_content_mgt_response { [] }
		.application_vnd_gmx { ['gmx'] }
		.application_vnd_gnu_taler_exchange_json { [] }
		.application_vnd_gnu_taler_merchant_json { [] }
		.application_vnd_google_earth_kml_xml { ['kml'] }
		.application_vnd_google_earth_kmz { ['kmz'] }
		.application_vnd_gov_sk_e_form_xml { [] }
		.application_vnd_gov_sk_e_form_zip { [] }
		.application_vnd_gov_sk_xmldatacontainer_xml { [] }
		.application_vnd_gp3 { [] }
		.application_vnd_gpxsee_map_xml { [] }
		.application_vnd_grafeq { ['gqf', 'gqs'] }
		.application_vnd_gridmp { [] }
		.application_vnd_groove_account { ['gac'] }
		.application_vnd_groove_help { ['ghf'] }
		.application_vnd_groove_identity_message { ['gim'] }
		.application_vnd_groove_injector { ['grv'] }
		.application_vnd_groove_tool_message { ['gtm'] }
		.application_vnd_groove_tool_template { ['tpl'] }
		.application_vnd_groove_vcard { ['vcg'] }
		.application_vnd_hal_json { ['hal'] }
		.application_vnd_hal_xml { ['hal'] }
		.application_vnd_hand_held_entertainment_xml { ['zmm'] }
		.application_vnd_hbci { ['hbci'] }
		.application_vnd_hc_json { [] }
		.application_vnd_hcl_bireports { [] }
		.application_vnd_hdfgroup_hdf4 { ['hdf'] }
		.application_vnd_hdfgroup_hdf5 { ['hdf5', 'h5'] }
		.application_vnd_hdt { ['hdt'] }
		.application_vnd_heroku_json { [] }
		.application_vnd_hhe_lesson_player { ['les'] }
		.application_vnd_hp_hpgl { ['hpgl'] }
		.application_vnd_hp_hpid { ['hpid'] }
		.application_vnd_hp_hps { ['hps'] }
		.application_vnd_hp_jlyt { ['jlt'] }
		.application_vnd_hp_pcl { ['pcl'] }
		.application_vnd_hp_pclxl { ['pclxl'] }
		.application_vnd_hsl { [] }
		.application_vnd_httphone { [] }
		.application_vnd_hydrostatix_sof_data { ['sfd-hdstx'] }
		.application_vnd_hyper_item_json { [] }
		.application_vnd_hyper_json { [] }
		.application_vnd_hyperdrive_json { [] }
		.application_vnd_hzn_3d_crossword { [] }
		.application_vnd_ibm_afplinedata { [] }
		.application_vnd_ibm_electronic_media { [] }
		.application_vnd_ibm_mini_pay { ['mpy'] }
		.application_vnd_ibm_modcap { ['afp', 'listafp', 'list3820'] }
		.application_vnd_ibm_rights_management { ['irm'] }
		.application_vnd_ibm_secure_container { ['sc'] }
		.application_vnd_iccprofile { ['icc', 'icm'] }
		.application_vnd_ieee_1905 { [] }
		.application_vnd_igloader { ['igl'] }
		.application_vnd_imagemeter_folder_zip { [] }
		.application_vnd_imagemeter_image_zip { [] }
		.application_vnd_immervision_ivp { ['ivp'] }
		.application_vnd_immervision_ivu { ['ivu'] }
		.application_vnd_ims_imsccv1p1 { [] }
		.application_vnd_ims_imsccv1p2 { [] }
		.application_vnd_ims_imsccv1p3 { [] }
		.application_vnd_ims_lis_v2_result_json { [] }
		.application_vnd_ims_lti_v2_toolconsumerprofile_json { [] }
		.application_vnd_ims_lti_v2_toolproxy_id_json { [] }
		.application_vnd_ims_lti_v2_toolproxy_json { [] }
		.application_vnd_ims_lti_v2_toolsettings_json { [] }
		.application_vnd_ims_lti_v2_toolsettings_simple_json { [] }
		.application_vnd_informedcontrol_rms_xml { [] }
		.application_vnd_infotech_project { [] }
		.application_vnd_infotech_project_xml { [] }
		.application_vnd_informix_visionary { [] }
		.application_vnd_innopath_wamp_notification { [] }
		.application_vnd_insors_igm { ['igm'] }
		.application_vnd_intercon_formnet { ['xpw', 'xpx'] }
		.application_vnd_intergeo { ['i2g'] }
		.application_vnd_intertrust_digibox { [] }
		.application_vnd_intertrust_nncp { [] }
		.application_vnd_intu_qbo { ['qbo'] }
		.application_vnd_intu_qfx { ['qfx'] }
		.application_vnd_ipfs_ipns_record { [] }
		.application_vnd_ipld_car { [] }
		.application_vnd_ipld_dag_cbor { [] }
		.application_vnd_ipld_dag_json { [] }
		.application_vnd_ipld_raw { [] }
		.application_vnd_iptc_g2_catalogitem_xml { [] }
		.application_vnd_iptc_g2_conceptitem_xml { [] }
		.application_vnd_iptc_g2_knowledgeitem_xml { [] }
		.application_vnd_iptc_g2_newsitem_xml { [] }
		.application_vnd_iptc_g2_newsmessage_xml { [] }
		.application_vnd_iptc_g2_packageitem_xml { [] }
		.application_vnd_iptc_g2_planningitem_xml { [] }
		.application_vnd_ipunplugged_rcprofile { ['rcprofile'] }
		.application_vnd_irepository_package_xml { ['irp'] }
		.application_vnd_is_xpr { ['xpr'] }
		.application_vnd_isac_fcs { ['fcs'] }
		.application_vnd_jam { ['jam'] }
		.application_vnd_iso11783_10_zip { [] }
		.application_vnd_japannet_directory_service { [] }
		.application_vnd_japannet_jpnstore_wakeup { [] }
		.application_vnd_japannet_payment_wakeup { [] }
		.application_vnd_japannet_registration { [] }
		.application_vnd_japannet_registration_wakeup { [] }
		.application_vnd_japannet_setstore_wakeup { [] }
		.application_vnd_japannet_verification { [] }
		.application_vnd_japannet_verification_wakeup { [] }
		.application_vnd_jcp_javame_midlet_rms { ['rms'] }
		.application_vnd_jisp { ['jisp'] }
		.application_vnd_joost_joda_archive { ['joda'] }
		.application_vnd_jsk_isdn_ngn { [] }
		.application_vnd_kahootz { ['ktz', 'ktr'] }
		.application_vnd_kde_karbon { ['karbon'] }
		.application_vnd_kde_kchart { ['chrt'] }
		.application_vnd_kde_kformula { ['kfo'] }
		.application_vnd_kde_kivio { ['flw'] }
		.application_vnd_kde_kontour { ['kon'] }
		.application_vnd_kde_kpresenter { ['kpr', 'kpt'] }
		.application_vnd_kde_kspread { ['ksp'] }
		.application_vnd_kde_kword { ['kwd', 'kwt'] }
		.application_vnd_kdl { [] }
		.application_vnd_kenameaapp { ['htke'] }
		.application_vnd_keyman_kmp_zip { ['kmp'] }
		.application_vnd_keyman_kmx { ['kmx'] }
		.application_vnd_kidspiration { ['kia'] }
		.application_vnd_kinar { ['kne', 'knp'] }
		.application_vnd_koan { ['skp', 'skd', 'skt', 'skm'] }
		.application_vnd_kodak_descriptor { ['sse'] }
		.application_vnd_las { [] }
		.application_vnd_las_las_json { [] }
		.application_vnd_las_las_xml { [] }
		.application_vnd_laszip { ['laz'] }
		.application_vnd_ldev_productlicensing { [] }
		.application_vnd_leap_json { [] }
		.application_vnd_liberty_request_xml { [] }
		.application_vnd_llamagraphics_life_balance_desktop { ['lbd'] }
		.application_vnd_llamagraphics_life_balance_exchange_xml { ['lbe'] }
		.application_vnd_logipipe_circuit_zip { ['circle'] }
		.application_vnd_loom { [] }
		.application_vnd_lotus_1_2_3 { ['123'] }
		.application_vnd_lotus_approach { ['apr'] }
		.application_vnd_lotus_freelance { ['pre'] }
		.application_vnd_lotus_notes { ['nsf'] }
		.application_vnd_lotus_organizer { ['org'] }
		.application_vnd_lotus_screencam { ['scm'] }
		.application_vnd_lotus_wordpro { ['lwp'] }
		.application_vnd_lukuid_package_zip { [] }
		.application_vnd_macports_portpkg { ['portpkg'] }
		.application_vnd_majikah_bundle { [] }
		.application_vnd_maml { [] }
		.application_vnd_mapbox_vector_tile { ['mvt'] }
		.application_vnd_marlin_drm_actiontoken_xml { [] }
		.application_vnd_marlin_drm_conftoken_xml { [] }
		.application_vnd_marlin_drm_license_xml { [] }
		.application_vnd_marlin_drm_mdcf { [] }
		.application_vnd_mason_json { [] }
		.application_vnd_maxar_archive_3tz_zip { [] }
		.application_vnd_maxmind_maxmind_db { ['mmdb'] }
		.application_vnd_mcd { ['mcd'] }
		.application_vnd_mdl { ['mdl'] }
		.application_vnd_mdl_mbsdf { [] }
		.application_vnd_medcalcdata { ['mc1'] }
		.application_vnd_mediastation_cdkey { ['cdkey'] }
		.application_vnd_medicalholodeck_recordxr { [] }
		.application_vnd_meridian_slingshot { [] }
		.application_vnd_mermaid { ['mmd'] }
		.application_vnd_mfer { ['mwf'] }
		.application_vnd_mfmp { ['mfm'] }
		.application_vnd_micro_json { [] }
		.application_vnd_micrografx_flo { ['flo'] }
		.application_vnd_micrografx_igx { ['igx'] }
		.application_vnd_microsoft_portable_executable { ['exe', 'dll', 'com', 'bat', 'msi'] }
		.application_vnd_microsoft_windows_thumbnail_cache { [] }
		.application_vnd_miele_json { [] }
		.application_vnd_mif { ['mif'] }
		.application_vnd_minisoft_hp3000_save { [] }
		.application_vnd_mitsubishi_misty_guard_trustweb { [] }
		.application_vnd_mobius_daf { ['daf'] }
		.application_vnd_mobius_dis { ['dis'] }
		.application_vnd_mobius_mbk { ['mbk'] }
		.application_vnd_mobius_mqy { ['mqy'] }
		.application_vnd_mobius_msl { ['msl'] }
		.application_vnd_mobius_plc { ['plc'] }
		.application_vnd_mobius_txf { ['txf'] }
		.application_vnd_modl { [] }
		.application_vnd_mophun_application { ['mpn'] }
		.application_vnd_mophun_certificate { ['mpc'] }
		.application_vnd_motorola_flexsuite { [] }
		.application_vnd_motorola_flexsuite_adsi { [] }
		.application_vnd_motorola_flexsuite_fis { [] }
		.application_vnd_motorola_flexsuite_gotap { [] }
		.application_vnd_motorola_flexsuite_kmr { [] }
		.application_vnd_motorola_flexsuite_ttc { [] }
		.application_vnd_motorola_flexsuite_wem { [] }
		.application_vnd_motorola_iprm { [] }
		.application_vnd_mozilla_xul_xml { ['xul'] }
		.application_vnd_ms_artgalry { ['cil'] }
		.application_vnd_ms_asf { ['asf'] }
		.application_vnd_ms_cab_compressed { ['cab'] }
		.application_vnd_ms_3mfdocument { ['3mf'] }
		.application_vnd_ms_excel { ['xls', 'xlm', 'xla', 'xlc', 'xlt', 'xlw'] }
		.application_vnd_ms_excel_addin_macro_enabled_12 { ['xlam'] }
		.application_vnd_ms_excel_sheet_binary_macro_enabled_12 { ['xlsb'] }
		.application_vnd_ms_excel_sheet_macro_enabled_12 { ['xlsm'] }
		.application_vnd_ms_excel_template_macro_enabled_12 { ['xltm'] }
		.application_vnd_ms_fontobject { ['eot'] }
		.application_vnd_ms_htmlhelp { ['chm'] }
		.application_vnd_ms_ims { ['ims'] }
		.application_vnd_ms_lrm { ['lrm'] }
		.application_vnd_ms_office_active_x_xml { [] }
		.application_vnd_ms_officetheme { ['thmx'] }
		.application_vnd_ms_playready_initiator_xml { [] }
		.application_vnd_ms_powerpoint { ['ppt', 'pps', 'pot'] }
		.application_vnd_ms_powerpoint_addin_macro_enabled_12 { ['ppam'] }
		.application_vnd_ms_powerpoint_presentation_macro_enabled_12 { ['pptm'] }
		.application_vnd_ms_powerpoint_slide_macro_enabled_12 { ['sldm'] }
		.application_vnd_ms_powerpoint_slideshow_macro_enabled_12 { ['ppsm'] }
		.application_vnd_ms_powerpoint_template_macro_enabled_12 { ['potm'] }
		.application_vnd_ms_print_device_capabilities_xml { [] }
		.application_vnd_ms_print_schema_ticket_xml { [] }
		.application_vnd_ms_project { ['mpp', 'mpt'] }
		.application_vnd_ms_tnef { ['tnef', 'tnf'] }
		.application_vnd_ms_windows_devicepairing { [] }
		.application_vnd_ms_windows_nwprinting_oob { [] }
		.application_vnd_ms_windows_printerpairing { [] }
		.application_vnd_ms_windows_wsd_oob { [] }
		.application_vnd_ms_wmdrm_lic_chlg_req { [] }
		.application_vnd_ms_wmdrm_lic_resp { [] }
		.application_vnd_ms_wmdrm_meter_chlg_req { [] }
		.application_vnd_ms_wmdrm_meter_resp { [] }
		.application_vnd_ms_word_document_macro_enabled_12 { ['docm'] }
		.application_vnd_ms_word_template_macro_enabled_12 { ['dotm'] }
		.application_vnd_ms_works { ['wps', 'wks', 'wcm', 'wdb'] }
		.application_vnd_ms_wpl { ['wpl'] }
		.application_vnd_ms_xpsdocument { ['xps'] }
		.application_vnd_msa_disk_image { [] }
		.application_vnd_mseq { ['mseq'] }
		.application_vnd_msgpack { ['msgpack'] }
		.application_vnd_msign { [] }
		.application_vnd_multiad_creator { [] }
		.application_vnd_multiad_creator_cif { [] }
		.application_vnd_musician { ['mus'] }
		.application_vnd_music_niff { ['niff'] }
		.application_vnd_muvee_style { ['msty'] }
		.application_vnd_mynfc { ['taglet'] }
		.application_vnd_nacamar_ybrid_json { [] }
		.application_vnd_nato_bindingdataobject_cbor { [] }
		.application_vnd_nato_bindingdataobject_json { [] }
		.application_vnd_nato_bindingdataobject_xml { [] }
		.application_vnd_nato_openxmlformats_package_iepd_zip { [] }
		.application_vnd_ncd_control { [] }
		.application_vnd_ncd_reference { [] }
		.application_vnd_nearst_inv_json { [] }
		.application_vnd_nebumind_line { [] }
		.application_vnd_nervana { [] }
		.application_vnd_netfpx { [] }
		.application_vnd_neurolanguage_nlu { ['nlu'] }
		.application_vnd_nila_protobuf_bundle_zip { [] }
		.application_vnd_nimn { [] }
		.application_vnd_nintendo_snes_rom { ['sfc', 'smc'] }
		.application_vnd_nintendo_nitro_rom { ['nds'] }
		.application_vnd_nitf { ['ntf', 'nitf'] }
		.application_vnd_noblenet_directory { ['nnd'] }
		.application_vnd_noblenet_sealer { ['nns'] }
		.application_vnd_noblenet_web { ['nnw'] }
		.application_vnd_nokia_catalogs { [] }
		.application_vnd_nokia_conml_wbxml { [] }
		.application_vnd_nokia_conml_xml { [] }
		.application_vnd_nokia_iptv_config_xml { [] }
		.application_vnd_nokia_i_sds_radio_presets { [] }
		.application_vnd_nokia_landmark_wbxml { [] }
		.application_vnd_nokia_landmark_xml { [] }
		.application_vnd_nokia_landmarkcollection_xml { [] }
		.application_vnd_nokia_ncd { [] }
		.application_vnd_nokia_n_gage_ac_xml { ['ac'] }
		.application_vnd_nokia_n_gage_data { ['ngdat'] }
		.application_vnd_nokia_n_gage_symbian_install { ['n-gage'] }
		.application_vnd_nokia_pcd_wbxml { [] }
		.application_vnd_nokia_pcd_xml { [] }
		.application_vnd_nokia_radio_preset { ['rpst'] }
		.application_vnd_nokia_radio_presets { ['rpss'] }
		.application_vnd_novadigm_edm { ['edm'] }
		.application_vnd_novadigm_edx { ['edx'] }
		.application_vnd_novadigm_ext { ['ext'] }
		.application_vnd_ntt_local_content_share { [] }
		.application_vnd_ntt_local_file_transfer { [] }
		.application_vnd_ntt_local_ogw_remote_access { [] }
		.application_vnd_ntt_local_sip_ta_remote { [] }
		.application_vnd_ntt_local_sip_ta_tcp_stream { [] }
		.application_vnd_nubaltec_nudoku_game { [] }
		.application_vnd_oai_workflows { [] }
		.application_vnd_oai_workflows_json { [] }
		.application_vnd_oai_workflows_yaml { [] }
		.application_vnd_oasis_opendocument_base { [] }
		.application_vnd_oasis_opendocument_chart { ['odc'] }
		.application_vnd_oasis_opendocument_chart_template { ['otc'] }
		.application_vnd_oasis_opendocument_database { ['odb'] }
		.application_vnd_oasis_opendocument_formula { ['odf'] }
		.application_vnd_oasis_opendocument_formula_template { ['odft'] }
		.application_vnd_oasis_opendocument_graphics { ['odg'] }
		.application_vnd_oasis_opendocument_graphics_template { ['otg'] }
		.application_vnd_oasis_opendocument_image { ['odi'] }
		.application_vnd_oasis_opendocument_image_template { ['oti'] }
		.application_vnd_oasis_opendocument_presentation { ['odp'] }
		.application_vnd_oasis_opendocument_presentation_template { ['otp'] }
		.application_vnd_oasis_opendocument_spreadsheet { ['ods'] }
		.application_vnd_oasis_opendocument_spreadsheet_template { ['ots'] }
		.application_vnd_oasis_opendocument_text { ['odt'] }
		.application_vnd_oasis_opendocument_text_master { ['odm'] }
		.application_vnd_oasis_opendocument_text_master_template { [] }
		.application_vnd_oasis_opendocument_text_template { ['ott'] }
		.application_vnd_oasis_opendocument_text_web { ['oth'] }
		.application_vnd_obn { [] }
		.application_vnd_ocf_cbor { [] }
		.application_vnd_oci_image_manifest_v1_json { [] }
		.application_vnd_oftn_l10n_json { [] }
		.application_vnd_oipf_contentaccessdownload_xml { [] }
		.application_vnd_oipf_contentaccessstreaming_xml { [] }
		.application_vnd_oipf_cspg_hexbinary { [] }
		.application_vnd_oipf_dae_svg_xml { [] }
		.application_vnd_oipf_dae_xhtml_xml { [] }
		.application_vnd_oipf_mippvcontrolmessage_xml { [] }
		.application_vnd_oipf_pae_gem { [] }
		.application_vnd_oipf_spdiscovery_xml { [] }
		.application_vnd_oipf_spdlist_xml { [] }
		.application_vnd_oipf_ueprofile_xml { [] }
		.application_vnd_oipf_userprofile_xml { [] }
		.application_vnd_olpc_sugar { ['xo'] }
		.application_vnd_oma_bcast_associated_procedure_parameter_xml { [] }
		.application_vnd_oma_bcast_drm_trigger_xml { [] }
		.application_vnd_oma_bcast_imd_xml { [] }
		.application_vnd_oma_bcast_ltkm { [] }
		.application_vnd_oma_bcast_notification_xml { [] }
		.application_vnd_oma_bcast_provisioningtrigger { [] }
		.application_vnd_oma_bcast_sgboot { [] }
		.application_vnd_oma_bcast_sgdd_xml { [] }
		.application_vnd_oma_bcast_sgdu { [] }
		.application_vnd_oma_bcast_simple_symbol_container { [] }
		.application_vnd_oma_bcast_smartcard_trigger_xml { [] }
		.application_vnd_oma_bcast_sprov_xml { [] }
		.application_vnd_oma_bcast_stkm { [] }
		.application_vnd_oma_cab_address_book_xml { [] }
		.application_vnd_oma_cab_feature_handler_xml { [] }
		.application_vnd_oma_cab_pcc_xml { [] }
		.application_vnd_oma_cab_subs_invite_xml { [] }
		.application_vnd_oma_cab_user_prefs_xml { [] }
		.application_vnd_oma_dcd { [] }
		.application_vnd_oma_dcdc { [] }
		.application_vnd_oma_dd2_xml { ['dd2'] }
		.application_vnd_oma_drm_risd_xml { [] }
		.application_vnd_oma_group_usage_list_xml { [] }
		.application_vnd_oma_lwm2m_cbor { [] }
		.application_vnd_oma_lwm2m_json { [] }
		.application_vnd_oma_lwm2m_tlv { [] }
		.application_vnd_oma_pal_xml { [] }
		.application_vnd_oma_poc_detailed_progress_report_xml { [] }
		.application_vnd_oma_poc_final_report_xml { [] }
		.application_vnd_oma_poc_groups_xml { [] }
		.application_vnd_oma_poc_invocation_descriptor_xml { [] }
		.application_vnd_oma_poc_optimized_progress_report_xml { [] }
		.application_vnd_oma_push { [] }
		.application_vnd_oma_scidm_messages_xml { [] }
		.application_vnd_oma_xcap_directory_xml { [] }
		.application_vnd_omads_email_xml { [] }
		.application_vnd_omads_file_xml { [] }
		.application_vnd_omads_folder_xml { [] }
		.application_vnd_omaloc_supl_init { [] }
		.application_vnd_oma_scws_config { [] }
		.application_vnd_oma_scws_http_request { [] }
		.application_vnd_oma_scws_http_response { [] }
		.application_vnd_oms_cellular_cose_content_cbor { [] }
		.application_vnd_onepager { [] }
		.application_vnd_onepagertamp { [] }
		.application_vnd_onepagertamx { [] }
		.application_vnd_onepagertat { [] }
		.application_vnd_onepagertatp { [] }
		.application_vnd_onepagertatx { [] }
		.application_vnd_onvif_metadata { [] }
		.application_vnd_openblox_game_binary { [] }
		.application_vnd_openblox_game_xml { [] }
		.application_vnd_openeye_oeb { [] }
		.application_vnd_openprinttag { [] }
		.application_vnd_openstreetmap_data_xml { ['osm'] }
		.application_vnd_opentimestamps_ots { ['ots'] }
		.application_vnd_openvpi_dspx_json { [] }
		.application_vnd_openxmlformats_officedocument_custom_properties_xml { [] }
		.application_vnd_openxmlformats_officedocument_custom_xml_properties_xml { [] }
		.application_vnd_openxmlformats_officedocument_drawing_xml { [] }
		.application_vnd_openxmlformats_officedocument_drawingml_chart_xml { [] }
		.application_vnd_openxmlformats_officedocument_drawingml_chartshapes_xml { [] }
		.application_vnd_openxmlformats_officedocument_drawingml_diagram_colors_xml { [] }
		.application_vnd_openxmlformats_officedocument_drawingml_diagram_data_xml { [] }
		.application_vnd_openxmlformats_officedocument_drawingml_diagram_layout_xml { [] }
		.application_vnd_openxmlformats_officedocument_drawingml_diagram_style_xml { [] }
		.application_vnd_openxmlformats_officedocument_extended_properties_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_comment_authors_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_comments_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_handout_master_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_notes_master_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_notes_slide_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_presentation { ['pptx'] }
		.application_vnd_openxmlformats_officedocument_presentationml_presentation_main_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_pres_props_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_slide { ['sldx'] }
		.application_vnd_openxmlformats_officedocument_presentationml_slide_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_slide_layout_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_slide_master_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_slideshow { ['ppsx'] }
		.application_vnd_openxmlformats_officedocument_presentationml_slideshow_main_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_slide_update_info_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_table_styles_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_tags_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_template { ['potx'] }
		.application_vnd_openxmlformats_officedocument_presentationml_template_main_xml { [] }
		.application_vnd_openxmlformats_officedocument_presentationml_view_props_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_calc_chain_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_chartsheet_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_comments_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_connections_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_dialogsheet_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_external_link_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_pivot_cache_definition_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_pivot_cache_records_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_pivot_table_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_query_table_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_revision_headers_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_revision_log_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_shared_strings_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_sheet { ['xlsx'] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_sheet_main_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_sheet_metadata_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_styles_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_table_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_table_single_cells_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_template { ['xltx'] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_template_main_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_user_names_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_volatile_dependencies_xml { [] }
		.application_vnd_openxmlformats_officedocument_spreadsheetml_worksheet_xml { [] }
		.application_vnd_openxmlformats_officedocument_theme_xml { [] }
		.application_vnd_openxmlformats_officedocument_theme_override_xml { [] }
		.application_vnd_openxmlformats_officedocument_vml_drawing { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_comments_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_document { ['docx'] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_document_glossary_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_document_main_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_endnotes_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_font_table_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_footer_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_footnotes_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_numbering_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_settings_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_styles_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_template { ['dotx'] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_template_main_xml { [] }
		.application_vnd_openxmlformats_officedocument_wordprocessingml_web_settings_xml { [] }
		.application_vnd_openxmlformats_package_core_properties_xml { [] }
		.application_vnd_openxmlformats_package_digital_signature_xmlsignature_xml { [] }
		.application_vnd_openxmlformats_package_relationships_xml { [] }
		.application_vnd_oracle_resource_json { [] }
		.application_vnd_orange_indata { [] }
		.application_vnd_osa_netdeploy { [] }
		.application_vnd_osgeo_mapguide_package { ['mgp'] }
		.application_vnd_osgi_bundle { [] }
		.application_vnd_osgi_dp { ['dp'] }
		.application_vnd_osgi_subsystem { ['esa'] }
		.application_vnd_otps_ct_kip_xml { [] }
		.application_vnd_oxli_countgraph { [] }
		.application_vnd_pagerduty_json { [] }
		.application_vnd_palm { ['pdb', 'pqa', 'oprc'] }
		.application_vnd_panoply { [] }
		.application_vnd_paos_xml { [] }
		.application_vnd_patentdive { [] }
		.application_vnd_patientecommsdoc { [] }
		.application_vnd_pawaafile { ['paw'] }
		.application_vnd_pcos { [] }
		.application_vnd_pg_format { ['str'] }
		.application_vnd_pg_osasli { ['ei6'] }
		.application_vnd_phbk_xml { [] }
		.application_vnd_piaccess_application_licence { [] }
		.application_vnd_picsel { ['efif'] }
		.application_vnd_pmi_widget { ['wg'] }
		.application_vnd_pmtiles { ['pmtiles'] }
		.application_vnd_poc_group_advertisement_xml { [] }
		.application_vnd_pocketlearn { ['plf'] }
		.application_vnd_powerbuilder6 { ['pbd'] }
		.application_vnd_powerbuilder6_s { [] }
		.application_vnd_powerbuilder7 { [] }
		.application_vnd_powerbuilder75 { [] }
		.application_vnd_powerbuilder75_s { [] }
		.application_vnd_powerbuilder7_s { [] }
		.application_vnd_pp_systemverify_xml { [] }
		.application_vnd_preminet { [] }
		.application_vnd_previewsystems_box { ['box'] }
		.application_vnd_project_graph { [] }
		.application_vnd_proteus_magazine { ['mgz'] }
		.application_vnd_psfs { [] }
		.application_vnd_pt_mundusmundi { [] }
		.application_vnd_publishare_delta_tree { ['qps'] }
		.application_vnd_pvi_ptid1 { ['ptid'] }
		.application_vnd_pwg_multiplexed { [] }
		.application_vnd_pwg_xhtml_print_xml { [] }
		.application_vnd_pyon_json { [] }
		.application_vnd_qualcomm_brew_app_res { ['bar'] }
		.application_vnd_quarantainenet { [] }
		.application_vnd_quark_quark_x_press { ['qxd', 'qxt', 'qwd', 'qwt', 'qxl', 'qxb'] }
		.application_vnd_quobject_quoxdocument { [] }
		.application_vnd_r74n_sandboxels_json { [] }
		.application_vnd_radisys_moml_xml { [] }
		.application_vnd_radisys_msml_audit_conf_xml { [] }
		.application_vnd_radisys_msml_audit_conn_xml { [] }
		.application_vnd_radisys_msml_audit_dialog_xml { [] }
		.application_vnd_radisys_msml_audit_stream_xml { [] }
		.application_vnd_radisys_msml_audit_xml { [] }
		.application_vnd_radisys_msml_conf_xml { [] }
		.application_vnd_radisys_msml_dialog_base_xml { [] }
		.application_vnd_radisys_msml_dialog_fax_detect_xml { [] }
		.application_vnd_radisys_msml_dialog_fax_sendrecv_xml { [] }
		.application_vnd_radisys_msml_dialog_group_xml { [] }
		.application_vnd_radisys_msml_dialog_speech_xml { [] }
		.application_vnd_radisys_msml_dialog_transform_xml { [] }
		.application_vnd_radisys_msml_dialog_xml { [] }
		.application_vnd_radisys_msml_xml { [] }
		.application_vnd_rainstor_data { [] }
		.application_vnd_rapid { ['rpss'] }
		.application_vnd_rar { ['rar'] }
		.application_vnd_realvnc_bed { ['bed'] }
		.application_vnd_recordare_musicxml { ['mxl'] }
		.application_vnd_recordare_musicxml_xml { ['musicxml'] }
		.application_vnd_rego { [] }
		.application_vnd_relpipe { [] }
		.application_vnd_ren_learn_rlprint { [] }
		.application_vnd_resilient_logic { [] }
		.application_vnd_restful_json { [] }
		.application_vnd_rig_cryptonote { ['cryptonote'] }
		.application_vnd_route66_link66_xml { ['link66'] }
		.application_vnd_rs_274x { [] }
		.application_vnd_ruckus_download { [] }
		.application_vnd_s3sms { [] }
		.application_vnd_sailingtracker_track { ['st'] }
		.application_vnd_sar { [] }
		.application_vnd_sbm_cid { [] }
		.application_vnd_sbm_mid2 { [] }
		.application_vnd_scribus { ['sla'] }
		.application_vnd_sealed_3df { [] }
		.application_vnd_sealed_csf { [] }
		.application_vnd_sealed_doc { [] }
		.application_vnd_sealed_eml { [] }
		.application_vnd_sealed_mht { [] }
		.application_vnd_sealed_net { [] }
		.application_vnd_sealed_ppt { [] }
		.application_vnd_sealed_tiff { [] }
		.application_vnd_sealed_xls { [] }
		.application_vnd_sealedmedia_softseal_html { [] }
		.application_vnd_sealedmedia_softseal_pdf { [] }
		.application_vnd_seemail { ['see'] }
		.application_vnd_seis_json { [] }
		.application_vnd_sema { ['sema'] }
		.application_vnd_semd { ['semd'] }
		.application_vnd_semf { ['semf'] }
		.application_vnd_shade_save_file { [] }
		.application_vnd_shana_informed_formdata { ['ifm'] }
		.application_vnd_shana_informed_formtemplate { ['itp'] }
		.application_vnd_shana_informed_interchange { ['iif'] }
		.application_vnd_shana_informed_package { ['ipk'] }
		.application_vnd_shootproof_json { [] }
		.application_vnd_shopkick_json { [] }
		.application_vnd_shp { ['shp'] }
		.application_vnd_shx { ['shx'] }
		.application_vnd_sigrok_session { [] }
		.application_vnd_sim_tech_mind_mapper { ['twd', 'twds'] }
		.application_vnd_siren_json { [] }
		.application_vnd_sirtx_vmv0 { [] }
		.application_vnd_sketchometry { [] }
		.application_vnd_smaf { ['mmf'] }
		.application_vnd_smart_notebook { ['notebook'] }
		.application_vnd_smart_teacher { ['teacher'] }
		.application_vnd_smintio_portals_archive { [] }
		.application_vnd_snesdev_page_table { [] }
		.application_vnd_software602_filler_form_xml { ['fo'] }
		.application_vnd_software602_filler_form_xml_zip { [] }
		.application_vnd_solent_sdkm_xml { ['sdkm', 'sdkd'] }
		.application_vnd_spotfire_dxp { ['dxp'] }
		.application_vnd_spotfire_sfs { ['sfs'] }
		.application_vnd_sqlite3 { ['sqlite', 'db', 'sqlite3'] }
		.application_vnd_sri { [] }
		.application_vnd_sss_cod { [] }
		.application_vnd_sss_dtf { [] }
		.application_vnd_sss_ntf { [] }
		.application_vnd_stepmania_package { ['smzip'] }
		.application_vnd_stepmania_stepchart { ['sm'] }
		.application_vnd_street_stream { [] }
		.application_vnd_sun_wadl_xml { ['wadl'] }
		.application_vnd_superfile_super { [] }
		.application_vnd_sus_calendar { ['sus', 'susp'] }
		.application_vnd_svd { ['svd'] }
		.application_vnd_swiftview_ics { [] }
		.application_vnd_sybyl_mol2 { ['mol2'] }
		.application_vnd_sycle_xml { [] }
		.application_vnd_syft_json { [] }
		.application_vnd_syncml_dm_notification { [] }
		.application_vnd_syncml_dmddf_xml { ['ddf'] }
		.application_vnd_syncml_dmtnds_wbxml { [] }
		.application_vnd_syncml_dmtnds_xml { [] }
		.application_vnd_syncml_dmddf_wbxml { [] }
		.application_vnd_syncml_dm_wbxml { [] }
		.application_vnd_syncml_dm_xml { [] }
		.application_vnd_syncml_ds_notification { [] }
		.application_vnd_syncml_xml { ['xsm'] }
		.application_vnd_tableschema_json { [] }
		.application_vnd_tao_intent_module_archive { ['tao'] }
		.application_vnd_tcpdump_pcap { ['pcap', 'cap', 'dmp'] }
		.application_vnd_think_cell_ppttc_json { [] }
		.application_vnd_tml { [] }
		.application_vnd_tmd_mediaflex_api_xml { [] }
		.application_vnd_tmobile_livetv { ['tmo'] }
		.application_vnd_tri_onesource { [] }
		.application_vnd_trid_tpt { ['tpt'] }
		.application_vnd_triscape_mxs { ['mxs'] }
		.application_vnd_trueapp { ['tra'] }
		.application_vnd_truedoc { [] }
		.application_vnd_ubisoft_webplayer { [] }
		.application_vnd_ufdl { ['ufd', 'ufdl'] }
		.application_vnd_uic_dosipas_v1 { [] }
		.application_vnd_uic_dosipas_v2 { [] }
		.application_vnd_uic_osdm_json { [] }
		.application_vnd_uic_tlb_fcb { [] }
		.application_vnd_uiq_theme { ['uiq'] }
		.application_vnd_umajin { ['umj'] }
		.application_vnd_unity { ['unityweb'] }
		.application_vnd_uoml_xml { ['uoml'] }
		.application_vnd_uplanet_alert { [] }
		.application_vnd_uplanet_alert_wbxml { [] }
		.application_vnd_uplanet_bearer_choice { [] }
		.application_vnd_uplanet_bearer_choice_wbxml { [] }
		.application_vnd_uplanet_cacheop { [] }
		.application_vnd_uplanet_cacheop_wbxml { [] }
		.application_vnd_uplanet_channel { [] }
		.application_vnd_uplanet_channel_wbxml { [] }
		.application_vnd_uplanet_list { [] }
		.application_vnd_uplanet_listcmd { [] }
		.application_vnd_uplanet_listcmd_wbxml { [] }
		.application_vnd_uplanet_list_wbxml { [] }
		.application_vnd_uri_map { [] }
		.application_vnd_uplanet_signal { [] }
		.application_vnd_valve_source_material { ['vmt'] }
		.application_vnd_vcx { ['vcx'] }
		.application_vnd_vd_study { [] }
		.application_vnd_vectorworks { ['vwx'] }
		.application_vnd_vel_json { [] }
		.application_vnd_veraison_tsm_report_cbor { [] }
		.application_vnd_veraison_tsm_report_json { [] }
		.application_vnd_verifier_attestation_jwt { [] }
		.application_vnd_verimatrix_vcas { [] }
		.application_vnd_veritone_aion_json { [] }
		.application_vnd_vertifile_pvf { [] }
		.application_vnd_veryant_thin { [] }
		.application_vnd_ves_encrypted { [] }
		.application_vnd_vidsoft_vidconference { [] }
		.application_vnd_vimina_vma { [] }
		.application_vnd_visio { ['vsd', 'vst', 'vss', 'vsw'] }
		.application_vnd_visionary { ['vis'] }
		.application_vnd_vividence_scriptfile { [] }
		.application_vnd_vocalshaper_vsp4 { [] }
		.application_vnd_vsf { ['vsf'] }
		.application_vnd_vuq { [] }
		.application_vnd_wantverse { [] }
		.application_vnd_wap_sic { [] }
		.application_vnd_wap_slc { [] }
		.application_vnd_wap_wbxml { ['wbxml'] }
		.application_vnd_wap_wmlc { ['wmlc'] }
		.application_vnd_wap_wmlscriptc { ['wmlsc'] }
		.application_vnd_wasmflow_wafl { [] }
		.application_vnd_webturbo { ['wtb'] }
		.application_vnd_wfa_dpp { [] }
		.application_vnd_wfa_p2p { [] }
		.application_vnd_wfa_wsc { [] }
		.application_vnd_windows_devicepairing { [] }
		.application_vnd_wmap { [] }
		.application_vnd_wmc { [] }
		.application_vnd_wmf_bootstrap { [] }
		.application_vnd_wolfram_mathematica { ['nb'] }
		.application_vnd_wolfram_mathematica_package { ['m'] }
		.application_vnd_wolfram_player { ['nbp'] }
		.application_vnd_wordlift { [] }
		.application_vnd_wordperfect { ['wpd'] }
		.application_vnd_wqd { ['wqd'] }
		.application_vnd_wrq_hp3000_labelled { [] }
		.application_vnd_wt_stf { ['stf'] }
		.application_vnd_wv_csp_xml { [] }
		.application_vnd_wv_csp_wbxml { [] }
		.application_vnd_wv_ssp_xml { [] }
		.application_vnd_xacml_json { [] }
		.application_vnd_xara { ['xar'] }
		.application_vnd_xarin_cpj { [] }
		.application_vnd_xcdn { [] }
		.application_vnd_xecrets_encrypted { [] }
		.application_vnd_xfdl { ['xfdl'] }
		.application_vnd_xfdl_webform { [] }
		.application_vnd_xmi_xml { [] }
		.application_vnd_xmpie_cpkg { ['cpkg'] }
		.application_vnd_xmpie_dpkg { ['dpkg'] }
		.application_vnd_xmpie_plan { ['plan'] }
		.application_vnd_xmpie_ppkg { ['ppkg'] }
		.application_vnd_xmpie_xlim { ['xlim'] }
		.application_vnd_yamaha_hv_dic { ['hvd'] }
		.application_vnd_yamaha_hv_script { ['hvs'] }
		.application_vnd_yamaha_hv_voice { ['hvp'] }
		.application_vnd_yamaha_openscoreformat_osfpvg_xml { ['osfpvg'] }
		.application_vnd_yamaha_openscoreformat { ['osf'] }
		.application_vnd_yamaha_remote_setup { ['rms'] }
		.application_vnd_yamaha_smaf_audio { ['saf'] }
		.application_vnd_yamaha_smaf_phrase { ['spf'] }
		.application_vnd_yamaha_through_ngn { [] }
		.application_vnd_yamaha_tunnel_udpencap { [] }
		.application_vnd_yaoweme { [] }
		.application_vnd_yellowriver_custom_menu { ['cmp'] }
		.application_vnd_youtube_yt { ['yt'] }
		.application_vnd_zoho_document_writer { [] }
		.application_vnd_zoho_presentation_show { [] }
		.application_vnd_zoho_spreadsheetml_sheet { [] }
		.application_vnd_zul { ['zir', 'zirz'] }
		.application_vnd_zzazz_deck_xml { ['zaz'] }
		.application_voicexml_xml { ['vxml'] }
		.application_voucher_cms_json { [] }
		.application_voucher_jws_json { [] }
		.application_vp { [] }
		.application_vp_cose { [] }
		.application_vp_jwt { [] }
		.application_vp_sd_jwt { [] }
		.application_vq_rtcpxr { [] }
		.application_wasm { ['wasm'] }
		.application_watcherinfo_xml { ['wif'] }
		.application_webpush_options_json { [] }
		.application_whoispp_query { [] }
		.application_whoispp_response { [] }
		.application_widget { ['wgt'] }
		.application_wita { [] }
		.application_wordperfect5_1 { ['wp5'] }
		.application_wsdl_xml { ['wsdl'] }
		.application_wspolicy_xml { ['wspolicy'] }
		.application_x_pki_message { [] }
		.application_x_www_form_urlencoded { [] }
		.application_x_x509_ca_cert { ['crt', 'der'] }
		.application_x_x509_ca_ra_cert { [] }
		.application_x_x509_next_ca_cert { [] }
		.application_x400_bp { [] }
		.application_xacml_xml { [] }
		.application_xcap_att_xml { [] }
		.application_xcap_caps_xml { [] }
		.application_xcap_diff_xml { ['xdf'] }
		.application_xcap_el_xml { [] }
		.application_xcap_error_xml { [] }
		.application_xcap_ns_xml { [] }
		.application_xcon_conference_info_diff_xml { [] }
		.application_xcon_conference_info_xml { [] }
		.application_xenc_xml { ['xenc'] }
		.application_xfdf { ['xfdf'] }
		.application_xhtml_xml { ['xhtml', 'xht'] }
		.application_xliff_xml { ['xlf'] }
		.application_xml { ['xml', 'xsl', 'xsd', 'rng'] }
		.application_xml_dtd { ['dtd'] }
		.application_xml_external_parsed_entity { [] }
		.application_xml_patch_xml { [] }
		.application_xmpp_xml { [] }
		.application_xop_xml { ['xop'] }
		.application_xslt_xml { ['xslt', 'xsl'] }
		.application_xv_xml { ['mxml', 'xhvml', 'xvml', 'xvm'] }
		.application_yaml { ['yaml', 'yml'] }
		.application_yang { ['yang'] }
		.application_yang_data_cbor { [] }
		.application_yang_data_json { [] }
		.application_yang_data_xml { [] }
		.application_yang_patch_json { [] }
		.application_yang_patch_xml { [] }
		.application_yang_sid_json { [] }
		.application_yin_xml { ['yin'] }
		.application_zip { ['zip'] }
		.application_zlib { ['zz'] }
		.application_zstd { ['zst'] }
		.audio_1d_interleaved_parityfec { [] }
		.audio_32kadpcm { [] }
		.audio_3gpp { ['3gpp'] }
		.audio_3gpp2 { ['3g2'] }
		.audio_aac { ['aac'] }
		.audio_ac3 { ['ac3'] }
		.audio_amr { ['amr'] }
		.audio_amr_wb { ['awb'] }
		.audio_aptx { [] }
		.audio_asc { [] }
		.audio_atrac_advanced_lossless { [] }
		.audio_atrac_x { [] }
		.audio_atrac3 { [] }
		.audio_basic { ['au', 'snd'] }
		.audio_bv16 { [] }
		.audio_bv32 { [] }
		.audio_clearmode { [] }
		.audio_cn { [] }
		.audio_dat12 { [] }
		.audio_dls { [] }
		.audio_dsr_es201108 { [] }
		.audio_dsr_es202050 { [] }
		.audio_dsr_es202211 { [] }
		.audio_dsr_es202212 { [] }
		.audio_dv { [] }
		.audio_dvi4 { [] }
		.audio_eac3 { [] }
		.audio_encaprtp { [] }
		.audio_evrc { ['evc'] }
		.audio_evrc_qcp { [] }
		.audio_evrc0 { [] }
		.audio_evrc1 { [] }
		.audio_evrcb { [] }
		.audio_evrcb0 { [] }
		.audio_evrcb1 { [] }
		.audio_evrcnw { [] }
		.audio_evrcnw0 { [] }
		.audio_evrcnw1 { [] }
		.audio_evrcwb { [] }
		.audio_evrcwb0 { [] }
		.audio_evrcwb1 { [] }
		.audio_evs { [] }
		.audio_example { [] }
		.audio_flac { ['flac'] }
		.audio_flexfec { [] }
		.audio_fwdred { [] }
		.audio_g711_0 { [] }
		.audio_g719 { [] }
		.audio_g7221 { [] }
		.audio_g722 { [] }
		.audio_g723 { [] }
		.audio_g726_16 { [] }
		.audio_g726_24 { [] }
		.audio_g726_32 { [] }
		.audio_g726_40 { [] }
		.audio_g728 { [] }
		.audio_g729 { [] }
		.audio_g7291 { [] }
		.audio_g729_d { [] }
		.audio_g729_e { [] }
		.audio_gsm { ['gsm'] }
		.audio_gsm_efr { [] }
		.audio_gsm_hr_08 { [] }
		.audio_i_lbc { [] }
		.audio_ip_mr_v2_5 { [] }
		.audio_l8 { [] }
		.audio_l16 { [] }
		.audio_l20 { [] }
		.audio_l24 { [] }
		.audio_lpc { [] }
		.audio_matroska { ['mka'] }
		.audio_melp { [] }
		.audio_melp600 { [] }
		.audio_melp1200 { [] }
		.audio_melp2400 { [] }
		.audio_mhas { [] }
		.audio_midi_clip { [] }
		.audio_mobile_xmf { ['mxmf'] }
		.audio_mpa { [] }
		.audio_mp4 { ['m4a'] }
		.audio_mp4_a_latm { [] }
		.audio_mpa_robust { [] }
		.audio_mpeg { ['mpga', 'mp2', 'mp2a', 'mp3', 'm2a', 'm3a'] }
		.audio_mpeg4_generic { [] }
		.audio_ogg { ['oga', 'ogg', 'spx', 'opus'] }
		.audio_opus { ['opus'] }
		.audio_parityfec { [] }
		.audio_pcma { [] }
		.audio_pcma_wb { [] }
		.audio_pcmu { [] }
		.audio_pcmu_wb { [] }
		.audio_prs_sid { ['sid'] }
		.audio_qcelp { [] }
		.audio_raptorfec { [] }
		.audio_red { [] }
		.audio_rtp_enc_aescm128 { [] }
		.audio_rtploopback { [] }
		.audio_rtp_midi { [] }
		.audio_rtx { [] }
		.audio_scip { [] }
		.audio_smv { ['smv'] }
		.audio_smv0 { [] }
		.audio_smv_qcp { [] }
		.audio_sofa { ['sofa'] }
		.audio_soundfont { ['sf2'] }
		.audio_sp_midi { [] }
		.audio_speex { ['spx'] }
		.audio_t140c { [] }
		.audio_t38 { [] }
		.audio_telephone_event { [] }
		.audio_tetra_acelp { [] }
		.audio_tetra_acelp_bb { [] }
		.audio_tone { [] }
		.audio_tsvcis { [] }
		.audio_uemclip { [] }
		.audio_ulpfec { [] }
		.audio_usac { [] }
		.audio_vdvi { [] }
		.audio_vmr_wb { [] }
		.audio_vnd_3gpp_iufp { [] }
		.audio_vnd_4_sb { [] }
		.audio_vnd_audiokoz { [] }
		.audio_vnd_blockfact_facta { [] }
		.audio_vnd_celp { [] }
		.audio_vnd_cisco_nse { [] }
		.audio_vnd_cmles_radio_events { [] }
		.audio_vnd_cns_anp1 { [] }
		.audio_vnd_cns_inf1 { [] }
		.audio_vnd_dece_audio { ['uva', 'uvva'] }
		.audio_vnd_digital_winds { ['eol'] }
		.audio_vnd_dlna_adts { [] }
		.audio_vnd_dolby_heaac_1 { [] }
		.audio_vnd_dolby_heaac_2 { [] }
		.audio_vnd_dolby_mlp { [] }
		.audio_vnd_dolby_mps { [] }
		.audio_vnd_dolby_pl2 { [] }
		.audio_vnd_dolby_pl2x { [] }
		.audio_vnd_dolby_pl2z { [] }
		.audio_vnd_dolby_pulse_1 { [] }
		.audio_vnd_dra { ['dra'] }
		.audio_vnd_dts { ['dts'] }
		.audio_vnd_dts_hd { ['dtshd'] }
		.audio_vnd_dts_uhd { [] }
		.audio_vnd_dvb_file { [] }
		.audio_vnd_everad_plj { [] }
		.audio_vnd_hns_audio { [] }
		.audio_vnd_lucent_voice { ['lvp'] }
		.audio_vnd_ms_playready_media_pya { ['pya'] }
		.audio_vnd_nokia_mobile_xmf { [] }
		.audio_vnd_nortel_vbk { ['vbk'] }
		.audio_vnd_nuera_ecelp4800 { ['ecelp4800'] }
		.audio_vnd_nuera_ecelp7470 { ['ecelp7470'] }
		.audio_vnd_nuera_ecelp9600 { ['ecelp9600'] }
		.audio_vnd_octel_sbc { [] }
		.audio_vnd_presonus_multitrack { [] }
		.audio_vnd_qcelp { ['qcp'] }
		.audio_vnd_rhetorex_32kadpcm { [] }
		.audio_vnd_rip { ['rip'] }
		.audio_vnd_sealedmedia_softseal_mpeg { [] }
		.audio_vnd_vmx_cvsd { [] }
		.audio_vorbis { ['oga'] }
		.audio_vorbis_config { [] }
		.font_collection { ['ttc'] }
		.font_otf { ['otf'] }
		.font_sfnt { [] }
		.font_ttf { ['ttf'] }
		.font_woff { ['woff'] }
		.font_woff2 { ['woff2'] }
		.haptics_ivs { ['ivs'] }
		.haptics_hjif { ['hjif'] }
		.haptics_hmpg { ['hmpg'] }
		.image_aces { ['exr'] }
		.image_apng { ['apng'] }
		.image_avci { [] }
		.image_avcs { [] }
		.image_avif { ['avif'] }
		.image_bmp { ['bmp'] }
		.image_cgm { ['cgm'] }
		.image_dicom_rle { [] }
		.image_dpx { ['dpx'] }
		.image_emf { ['emf'] }
		.image_example { [] }
		.image_fits { ['fits', 'fit', 'fts'] }
		.image_g3fax { ['g3'] }
		.image_gif { ['gif'] }
		.image_heic { ['heic'] }
		.image_heic_sequence { [] }
		.image_heif { ['heif'] }
		.image_heif_sequence { [] }
		.image_hej2k { [] }
		.image_hsj2 { [] }
		.image_ief { ['ief'] }
		.image_j2c { ['j2c', 'j2k'] }
		.image_jaii { [] }
		.image_jais { [] }
		.image_jls { [] }
		.image_jp2 { ['jp2', 'jpg2'] }
		.image_jpeg { ['jpeg', 'jpg', 'jpe'] }
		.image_jph { [] }
		.image_jphc { [] }
		.image_jpm { ['jpm', 'jpgm'] }
		.image_jpx { ['jpx', 'jpf'] }
		.image_jxl { ['jxl'] }
		.image_jxr { ['jxr'] }
		.image_jxr_a { [] }
		.image_jxr_s { [] }
		.image_jxs { [] }
		.image_jxsc { [] }
		.image_jxsi { [] }
		.image_jxss { [] }
		.image_ktx { ['ktx'] }
		.image_ktx2 { ['ktx2'] }
		.image_naplps { [] }
		.image_png { ['png'] }
		.image_prs_btif { ['btif'] }
		.image_prs_pti { ['pti'] }
		.image_pwg_raster { [] }
		.image_svg_xml { ['svg', 'svgz'] }
		.image_t38 { [] }
		.image_tiff { ['tiff', 'tif'] }
		.image_tiff_fx { [] }
		.image_vnd_adobe_photoshop { ['psd'] }
		.image_vnd_airzip_accelerator_azv { ['azv'] }
		.image_vnd_blockfact_facti { [] }
		.image_vnd_clip { [] }
		.image_vnd_cns_inf2 { [] }
		.image_vnd_dece_graphic { ['uvi', 'uvvi', 'uvg', 'uvvg'] }
		.image_vnd_djvu { ['djvu', 'djv'] }
		.image_vnd_dwg { ['dwg'] }
		.image_vnd_dxf { ['dxf'] }
		.image_vnd_dvb_subtitle { ['sub'] }
		.image_vnd_fastbidsheet { ['fbs'] }
		.image_vnd_fpx { ['fpx'] }
		.image_vnd_fst { ['fst'] }
		.image_vnd_fujixerox_edmics_mmr { ['mmr'] }
		.image_vnd_fujixerox_edmics_rlc { ['rlc'] }
		.image_vnd_globalgraphics_pgb { [] }
		.image_vnd_microsoft_icon { ['ico'] }
		.image_vnd_mix { [] }
		.image_vnd_ms_modi { ['mdi'] }
		.image_vnd_mozilla_apng { [] }
		.image_vnd_net_fpx { ['npx'] }
		.image_vnd_pco_b16 { ['b16'] }
		.image_vnd_radiance { ['hdr', 'rgbe', 'xyze'] }
		.image_vnd_sealed_png { [] }
		.image_vnd_sealedmedia_softseal_gif { [] }
		.image_vnd_sld { ['sld'] }
		.image_vnd_sealedmedia_softseal_jpg { [] }
		.image_vnd_svf { [] }
		.image_vnd_tencent_tap { ['vtf'] }
		.image_vnd_valve_source_texture { ['vtf'] }
		.image_vnd_wap_wbmp { ['wbmp'] }
		.image_vnd_xiff { ['xif'] }
		.image_vnd_zbrush_pcx { ['pcx'] }
		.image_webp { ['webp'] }
		.image_wmf { ['wmf'] }
		.image_x_emf { ['emf'] }
		.image_x_wmf { ['wmf'] }
		.message_bhttp { [] }
		.message_cpim { [] }
		.message_delivery_status { [] }
		.message_disposition_notification { [] }
		.message_example { [] }
		.message_external_body { [] }
		.message_feedback_report { [] }
		.message_global { [] }
		.message_global_delivery_status { [] }
		.message_global_disposition_notification { [] }
		.message_global_headers { [] }
		.message_http { [] }
		.message_imdn_xml { [] }
		.message_mls { [] }
		.message_news { [] }
		.message_ohttp_chunked_req { [] }
		.message_ohttp_chunked_res { [] }
		.message_ohttp_req { [] }
		.message_ohttp_res { [] }
		.message_partial { [] }
		.message_rfc822 { ['eml', 'mime'] }
		.message_s_http { [] }
		.message_sip { [] }
		.message_sipfrag { [] }
		.message_tracking_status { [] }
		.message_vnd_si_simp { [] }
		.message_vnd_wfa_wsc { [] }
		.model_3mf { ['3mf'] }
		.model_e57 { ['e57'] }
		.model_example { [] }
		.model_gltf_binary { ['glb'] }
		.model_gltf_json { ['gltf'] }
		.model_jt { ['jt'] }
		.model_iges { ['igs', 'iges'] }
		.model_mesh { ['msh', 'mesh', 'silo'] }
		.model_mtl { ['mtl'] }
		.model_obj { ['obj'] }
		.model_prc { ['prc'] }
		.model_step { ['step', 'stp'] }
		.model_step_xml { [] }
		.model_step_zip { [] }
		.model_step_xml_zip { [] }
		.model_stl { ['stl'] }
		.model_u3d { ['u3d'] }
		.model_vnd_bary { ['bary'] }
		.model_vnd_cld { [] }
		.model_vnd_collada_xml { ['dae'] }
		.model_vnd_dwf { ['dwf'] }
		.model_vnd_flatland_3dml { [] }
		.model_vnd_gdl { ['gdl'] }
		.model_vnd_gs_gdl { [] }
		.model_vnd_gtw { ['gtw'] }
		.model_vnd_moml_xml { [] }
		.model_vnd_mts { ['mts'] }
		.model_vnd_opengex { ['ogex'] }
		.model_vnd_parasolid_transmit_binary { ['x_b'] }
		.model_vnd_parasolid_transmit_text { ['x_t'] }
		.model_vnd_pytha_pyox { [] }
		.model_vnd_rosette_annotated_data_model { [] }
		.model_vnd_sap_vds { ['vds'] }
		.model_vnd_usda { ['usda'] }
		.model_vnd_usdz_zip { ['usdz'] }
		.model_vnd_valve_source_compiled_map { ['bsp'] }
		.model_vnd_vtu { ['vtu'] }
		.model_vrml { ['wrl', 'vrml'] }
		.model_x3d_vrml { ['x3dv'] }
		.model_x3d_fastinfoset { ['x3db'] }
		.model_x3d_xml { ['x3d'] }
		.multipart_alternative { [] }
		.multipart_appledouble { [] }
		.multipart_byteranges { [] }
		.multipart_digest { [] }
		.multipart_encrypted { [] }
		.multipart_example { [] }
		.multipart_form_data { [] }
		.multipart_header_set { [] }
		.multipart_mixed { [] }
		.multipart_multilingual { [] }
		.multipart_parallel { [] }
		.multipart_related { [] }
		.multipart_report { [] }
		.multipart_signed { [] }
		.multipart_vnd_bint_med_plus { [] }
		.multipart_voice_message { [] }
		.multipart_x_mixed_replace { [] }
		.text_1d_interleaved_parityfec { [] }
		.text_cache_manifest { ['appcache', 'manifest'] }
		.text_calendar { ['ics', 'ifb'] }
		.text_cql { ['cql'] }
		.text_cql_expression { [] }
		.text_cql_identifier { [] }
		.text_css { ['css'] }
		.text_csv { ['csv'] }
		.text_csv_schema { [] }
		.text_directory { [] }
		.text_dns { [] }
		.text_ecmascript { [] }
		.text_encaprtp { [] }
		.text_enriched { [] }
		.text_example { [] }
		.text_fhirpath { [] }
		.text_flexfec { [] }
		.text_fwdred { [] }
		.text_gff3 { ['gff3'] }
		.text_grammar_ref_list { [] }
		.text_hl7v2 { [] }
		.text_html { ['html', 'htm'] }
		.text_javascript { ['js', 'mjs'] }
		.text_jcr_cnd { ['cnd'] }
		.text_markdown { ['md', 'markdown'] }
		.text_mizar { ['miz'] }
		.text_n3 { ['n3'] }
		.text_org { ['org'] }
		.text_parameters { [] }
		.text_parityfec { [] }
		.text_plain { ['txt', 'text', 'conf', 'def', 'list', 'log', 'in'] }
		.text_provenance_notation { ['provn'] }
		.text_prs_fallenstein_rst { ['rst'] }
		.text_prs_lines_tag { ['dsc'] }
		.text_prs_prop_logic { [] }
		.text_prs_texi { ['texi', 'texinfo'] }
		.text_raptorfec { [] }
		.text_red { [] }
		.text_rfc822_headers { [] }
		.text_richtext { ['rtx'] }
		.text_rtf { ['rtf'] }
		.text_rtp_enc_aescm128 { [] }
		.text_rtploopback { [] }
		.text_rtx { [] }
		.text_sgml { ['sgml', 'sgm'] }
		.text_shaclc { [] }
		.text_shex { ['shex'] }
		.text_spdx { [] }
		.text_strings { [] }
		.text_t140 { [] }
		.text_tab_separated_values { ['tsv'] }
		.text_troff { ['t', 'tr', 'roff', 'man', 'me', 'ms'] }
		.text_turtle { ['ttl'] }
		.text_ulpfec { [] }
		.text_uri_list { ['uri', 'uris', 'urls'] }
		.text_vcard { ['vcard', 'vcf'] }
		.text_vnd_a { [] }
		.text_vnd_abc { [] }
		.text_vnd_ascii_art { [] }
		.text_vnd_curl { ['curl'] }
		.text_vnd_debian_copyright { [] }
		.text_vnd_dm_client_script { [] }
		.text_vnd_dvb_subtitle { ['sub'] }
		.text_vnd_esmertec_theme_descriptor { [] }
		.text_vnd_exchangeable { [] }
		.text_vnd_familysearch_gedcom { ['ged'] }
		.text_vnd_ficlab_flt { ['flt'] }
		.text_vnd_fly { ['fly'] }
		.text_vnd_fmi_flexstor { ['flx'] }
		.text_vnd_gml { [] }
		.text_vnd_graphviz { ['gv', 'dot'] }
		.text_vnd_hans { [] }
		.text_vnd_hekaya { [] }
		.text_vnd_hgl { [] }
		.text_vnd_in3d_3dml { ['3dml'] }
		.text_vnd_in3d_spot { ['spot'] }
		.text_vnd_iptc_news_ml { [] }
		.text_vnd_iptc_nitf { [] }
		.text_vnd_latex_z { [] }
		.text_vnd_longform { [] }
		.text_vnd_motorola_reflex { [] }
		.text_vnd_ms_mediapackage { [] }
		.text_vnd_net2phone_commcenter_command { [] }
		.text_vnd_radisys_msml_basic_layout { [] }
		.text_vnd_senx_warpscript { [] }
		.text_vnd_si_uricatalogue { [] }
		.text_vnd_sun_j2me_app_descriptor { ['jad'] }
		.text_vnd_sosi { ['sos'] }
		.text_vnd_tps { [] }
		.text_vnd_typst { ['typ'] }
		.text_vnd_trolltech_linguist { ['ts'] }
		.text_vnd_vcf { ['vcf'] }
		.text_vnd_vri { [] }
		.text_vnd_wap_si { ['si'] }
		.text_vnd_wap_sl { ['sl'] }
		.text_vnd_wap_wml { ['wml'] }
		.text_vnd_wap_wmlscript { ['wmls'] }
		.text_vnd_zoo_kcl { [] }
		.text_vtt { ['vtt'] }
		.text_wgsl { ['wgsl'] }
		.text_xml { ['xml'] }
		.text_xml_external_parsed_entity { [] }
		.video_1d_interleaved_parityfec { [] }
		.video_3gpp { ['3gp', '3gpp'] }
		.video_3gpp2 { ['3g2', '3gp2'] }
		.video_3gpp_tt { [] }
		.video_av1 { ['av1'] }
		.video_bmpeg { [] }
		.video_bt656 { [] }
		.video_cel_b { [] }
		.video_dv { ['dv'] }
		.video_encaprtp { [] }
		.video_evc { [] }
		.video_example { [] }
		.video_ffv1 { ['ffv1'] }
		.video_flexfec { [] }
		.video_h261 { ['h261'] }
		.video_h263 { ['h263'] }
		.video_h263_1998 { [] }
		.video_h263_2000 { [] }
		.video_h264 { ['h264'] }
		.video_h264_rcdo { [] }
		.video_h264_svc { [] }
		.video_h265 { ['h265', 'hevc'] }
		.video_h266 { ['h266', 'vvc'] }
		.video_iso_segment { ['mp4', 'm4s'] }
		.video_jpeg { ['jpgv'] }
		.video_jpeg2000 { ['mj2', 'mjp2'] }
		.video_jpeg2000_scl { [] }
		.video_jxsv { [] }
		.video_lottie_json { [] }
		.video_matroska { ['mkv'] }
		.video_matroska_3d { ['mk3d'] }
		.video_mj2 { ['mj2', 'mjp2'] }
		.video_mp1_s { [] }
		.video_mp2_p { [] }
		.video_mp2_t { ['m2ts', 'ts'] }
		.video_mp4 { ['mp4', 'mp4v', 'mpg4'] }
		.video_mp4_v_es { [] }
		.video_mpv { [] }
		.video_mpeg { ['mpeg', 'mpg', 'mpe', 'mpa', 'm1v', 'm2v'] }
		.video_mpeg4_generic { [] }
		.video_nv { [] }
		.video_ogg { ['ogv'] }
		.video_parityfec { [] }
		.video_pointer { [] }
		.video_quicktime { ['qt', 'mov'] }
		.video_raptorfec { [] }
		.video_raw { [] }
		.video_rtp_enc_aescm128 { [] }
		.video_rtploopback { [] }
		.video_rtx { [] }
		.video_scip { [] }
		.video_smpte291 { [] }
		.video_smpte292_m { [] }
		.video_ulpfec { [] }
		.video_vc1 { ['vc1'] }
		.video_vc2 { [] }
		.video_vnd_blockfact_factv { [] }
		.video_vnd_cctv { [] }
		.video_vnd_dece_hd { ['uvh', 'uvvh'] }
		.video_vnd_dece_mobile { ['uvm', 'uvvm'] }
		.video_vnd_dece_mp4 { [] }
		.video_vnd_dece_pd { ['uvp', 'uvvp'] }
		.video_vnd_dece_sd { ['uvs', 'uvvs'] }
		.video_vnd_dece_video { ['uvv', 'uvvv'] }
		.video_vnd_directv_mpeg { [] }
		.video_vnd_directv_mpeg_tts { [] }
		.video_vnd_dlna_mpeg_tts { [] }
		.video_vnd_dvb_file { ['dvb'] }
		.video_vnd_fvt { ['fvt'] }
		.video_vnd_hns_video { [] }
		.video_vnd_iptvforum_1dparityfec_1010 { [] }
		.video_vnd_iptvforum_1dparityfec_2005 { [] }
		.video_vnd_iptvforum_2dparityfec_1010 { [] }
		.video_vnd_iptvforum_2dparityfec_2005 { [] }
		.video_vnd_iptvforum_ttsavc { [] }
		.video_vnd_iptvforum_ttsmpeg2 { [] }
		.video_vnd_motorola_video { [] }
		.video_vnd_motorola_videop { [] }
		.video_vnd_mpegurl { ['mxu', 'm4u'] }
		.video_vnd_ms_playready_media_pyv { ['pyv'] }
		.video_vnd_nokia_interleaved_multimedia { ['nim'] }
		.video_vnd_nokia_mp4vr { [] }
		.video_vnd_nokia_videovoip { [] }
		.video_vnd_objectvideo { ['dvd'] }
		.video_vnd_planar { [] }
		.video_vnd_radgamettools_bink { ['bik', 'bk2'] }
		.video_vnd_radgamettools_smacker { ['smk'] }
		.video_vnd_sealed_mpeg1 { [] }
		.video_vnd_sealed_mpeg4 { [] }
		.video_vnd_sealed_swf { [] }
		.video_vnd_sealedmedia_softseal_mov { [] }
		.video_vnd_uvvu_mp4 { ['uvu', 'uvvu'] }
		.video_vnd_youtube_yt { ['yt'] }
		.video_vnd_vivo { ['viv'] }
		.video_vp8 { ['vp8'] }
		.video_vp9 { ['vp9'] }
	}
}
