module mime

/**
  * Sources:
  *   - https://www.iana.org/assignments/media-types/application.csv
  *   - https://www.iana.org/assignments/media-types/audio.csv
  *   - https://www.iana.org/assignments/media-types/font.csv
  *   - https://www.iana.org/assignments/media-types/haptics.csv
  *   - https://www.iana.org/assignments/media-types/image.csv
  *   - https://www.iana.org/assignments/media-types/message.csv
  *   - https://www.iana.org/assignments/media-types/model.csv
  *   - https://www.iana.org/assignments/media-types/multipart.csv
  *   - https://www.iana.org/assignments/media-types/text.csv
  *   - https://www.iana.org/assignments/media-types/video.csv
**/
pub enum Mime {
    application_1d_interleaved_parityfec
    application_3gpdash_qoe_report_xml
    application_3gpp_ims_xml
    application_3gpp_mbs_object_manifest_json
    application_3gpp_mbs_user_service_descriptions_json
    application_3gpp_media_delivery_metrics_report_json
    application_3gpp_hal_json
    application_3gpp_hal_forms_json
    application_aas_zip
    application_a2_l
    application_ace_groupcomm_cbor
    application_ace_trl_cbor
    application_ace_cbor
    application_ace_json
    application_activemessage
    application_activity_json
    application_aif_cbor
    application_aif_json
    application_alto_cdni_json
    application_alto_cdnifilter_json
    application_alto_costmap_json
    application_alto_costmapfilter_json
    application_alto_directory_json
    application_alto_endpointprop_json
    application_alto_endpointpropparams_json
    application_alto_endpointcost_json
    application_alto_endpointcostparams_json
    application_alto_error_json
    application_alto_networkmapfilter_json
    application_alto_networkmap_json
    application_alto_propmap_json
    application_alto_propmapparams_json
    application_alto_tips_json
    application_alto_tipsparams_json
    application_alto_updatestreamcontrol_json
    application_alto_updatestreamparams_json
    application_aml
    application_andrew_inset
    application_applefile
    application_asyncapi_json
    application_asyncapi_yaml
    application_at_jwt
    application_atf
    application_atfx
    application_atom_xml
    application_atomcat_xml
    application_atomdeleted_xml
    application_atomicmail
    application_atomsvc_xml
    application_atsc_dwd_xml
    application_atsc_dynamic_event_message
    application_atsc_held_xml
    application_atsc_rdt_json
    application_atsc_rsat_xml
    application_atxml
    application_auth_policy_xml
    application_automationml_aml_xml
    application_automationml_amlx_zip
    application_bacnet_xdd_zip
    application_batch_smtp
    application_beep_xml
    application_bufr
    application_c2pa
    application_calendar_json
    application_calendar_xml
    application_call_completion
    application_cals_1840
    application_captive_json
    application_cbor
    application_cbor_seq
    application_cccex
    application_ccmp_xml
    application_ccxml_xml
    application_cda_xml
    application_cdfx_xml
    application_cdmi_capability
    application_cdmi_container
    application_cdmi_domain
    application_cdmi_object
    application_cdmi_queue
    application_cdni
    application_ce_cbor
    application_cea
    application_cea_2018_xml
    application_cellml_xml
    application_cfw
    application_cid
    application_cid_edhoc_cbor_seq
    application_city_json
    application_city_json_seq
    application_client_authentication_jwt
    application_cloudevents_batch_json
    application_cloudevents_json
    application_clr
    application_clue_info_xml
    application_clue_xml
    application_cmcd
    application_cms
    application_cmw_cbor
    application_cmw_cose
    application_cmw_json
    application_cmw_jws
    application_cnrp_xml
    application_coap_eap
    application_coap_group_json
    application_coap_payload
    application_commonground
    application_concise_problem_details_cbor
    application_conference_info_xml
    application_cpl_xml
    application_cose
    application_cose_key
    application_cose_key_set
    application_cose_x509
    application_csrattrs
    application_csta_xml
    application_cst_adata_xml
    application_csvm_json
    application_cwl
    application_cwl_json
    application_cwl_yaml
    application_cwt
    application_cybercash
    application_dash_xml
    application_dash_patch_xml
    application_dashdelta
    application_davmount_xml
    application_dca_rft
    application_dcd
    application_dec_dx
    application_dialog_info_xml
    application_dicom
    application_dicom_json
    application_dicom_xml
    application_did
    application_dii
    application_dit
    application_dns
    application_dns_json
    application_dns_message
    application_dots_cbor
    application_dpop_jwt
    application_dskpp_xml
    application_dssc_der
    application_dssc_xml
    application_dvcs
    application_eat_cwt
    application_eat_jwt
    application_eat_bun_cbor
    application_eat_bun_json
    application_eat_ucs_cbor
    application_eat_ucs_json
    application_ecmascript
    application_edhoc_cbor_seq
    application_edi_consent
    application_edifact
    application_edi_x12
    application_efi
    application_elm_json
    application_elm_xml
    application_emergency_call_data_cap_xml
    application_emergency_call_data_comment_xml
    application_emergency_call_data_control_xml
    application_emergency_call_data_device_info_xml
    application_emergency_call_data_e_call_msd
    application_emergency_call_data_legacy_esn_json
    application_emergency_call_data_provider_info_xml
    application_emergency_call_data_service_info_xml
    application_emergency_call_data_subscriber_info_xml
    application_emergency_call_data_veds_xml
    application_emma_xml
    application_emotionml_xml
    application_encaprtp
    application_entity_statement_jwt
    application_epp_xml
    application_epub_zip
    application_eshop
    application_example
    application_exi
    application_expect_ct_report_json
    application_explicit_registration_response_jwt
    application_express
    application_fastinfoset
    application_fastsoap
    application_fdf
    application_fdt_xml
    application_fhir_json
    application_fhir_xml
    application_fits
    application_flexfec
    application_font_sfnt
    application_font_tdpfr
    application_font_woff
    application_framework_attributes_xml
    application_geo_json
    application_geo_json_seq
    application_geofeed_csv
    application_geopackage_sqlite3
    application_geopose_json
    application_geoxacml_json
    application_geoxacml_xml
    application_gltf_buffer
    application_gml_xml
    application_gnap_binding_jws
    application_gnap_binding_jwsd
    application_gnap_binding_rotation_jws
    application_gnap_binding_rotation_jwsd
    application_grib
    application_gzip
    application_h224
    application_held_xml
    application_hl7v2_xml
    application_http
    application_hyperstudio
    application_ibe_key_request_xml
    application_ibe_pkg_reply_xml
    application_ibe_pp_data
    application_iges
    application_im_iscomposing_xml
    application_index
    application_index_cmd
    application_index_obj
    application_index_response
    application_index_vnd
    application_inkml_xml
    application_iotp
    application_ipfix
    application_ipp
    application_isup
    application_its_xml
    application_java_archive
    application_javascript
    application_jf2feed_json
    application_jose
    application_jose_json
    application_jrd_json
    application_jscalendar_json
    application_jscontact_json
    application_json
    application_json_patch_json
    application_json_patch_query_json
    application_json_seq
    application_jsonpath
    application_jwk_json
    application_jwk_set_json
    application_jwk_set_jwt
    application_jwt
    application_kb_jwt
    application_kbl_xml
    application_kpml_request_xml
    application_kpml_response_xml
    application_ld_json
    application_lgr_xml
    application_link_format
    application_linkset
    application_linkset_json
    application_load_control_xml
    application_logout_jwt
    application_lost_xml
    application_lostsync_xml
    application_lpf_zip
    application_lxf
    application_mac_binhex40
    application_macwriteii
    application_mads_xml
    application_manifest_json
    application_marc
    application_marcxml_xml
    application_mathematica
    application_mathml_xml
    application_mathml_content_xml
    application_mathml_presentation_xml
    application_mbms_associated_procedure_description_xml
    application_mbms_deregister_xml
    application_mbms_envelope_xml
    application_mbms_msk_response_xml
    application_mbms_msk_xml
    application_mbms_protection_description_xml
    application_mbms_reception_report_xml
    application_mbms_register_response_xml
    application_mbms_register_xml
    application_mbms_schedule_xml
    application_mbms_user_service_description_xml
    application_mbox
    application_measured_component_cbor
    application_measured_component_json
    application_media_control_xml
    application_media_policy_dataset_xml
    application_mediaservercontrol_xml
    application_merge_patch_json
    application_metalink4_xml
    application_mets_xml
    application_mf4
    application_mikey
    application_mipc
    application_missing_blocks_cbor_seq
    application_mmt_aei_xml
    application_mmt_usd_xml
    application_mods_xml
    application_moss_keys
    application_moss_signature
    application_mosskey_data
    application_mosskey_request
    application_mp21
    application_mp4
    application_mpeg4_generic
    application_mpeg4_iod
    application_mpeg4_iod_xmt
    application_mrb_consumer_xml
    application_mrb_publish_xml
    application_msc_ivr_xml
    application_msc_mixer_xml
    application_msword
    application_mud_json
    application_multipart_core
    application_mxf
    application_n_quads
    application_n_triples
    application_nasdata
    application_news_checkgroups
    application_news_groupinfo
    application_news_transmission
    application_nlsml_xml
    application_node
    application_nss
    application_oauth_authz_req_jwt
    application_oblivious_dns_message
    application_ocsp_request
    application_ocsp_response
    application_octet_stream
    application_oda
    application_odm_xml
    application_odx
    application_oebps_package_xml
    application_ogg
    application_ohttp_keys
    application_opc_nodeset_xml
    application_oscore
    application_oxps
    application_p21
    application_p21_zip
    application_p2p_overlay_xml
    application_parityfec
    application_passport
    application_patch_ops_error_xml
    application_pdf
    application_pdx
    application_pem_certificate_chain
    application_pgp_encrypted
    application_pgp_keys
    application_pgp_signature
    application_pidf_diff_xml
    application_pidf_xml
    application_pkcs10
    application_pkcs7_mime
    application_pkcs7_signature
    application_pkcs8
    application_pkcs8_encrypted
    application_pkcs12
    application_pkix_attr_cert
    application_pkix_cert
    application_pkix_crl
    application_pkix_pkipath
    application_pkixcmp
    application_pls_xml
    application_poc_settings_xml
    application_postscript
    application_ppsp_tracker_json
    application_private_token_issuer_directory
    application_private_token_request
    application_private_token_response
    application_problem_json
    application_problem_xml
    application_protobuf
    application_protobuf_json
    application_provenance_xml
    application_provided_claims_jwt
    application_prs_alvestrand_titrax_sheet
    application_prs_bwtc32key
    application_prs_cww
    application_prs_cyn
    application_prs_hpub_zip
    application_prs_implied_document_xml
    application_prs_implied_executable
    application_prs_implied_object_json
    application_prs_implied_object_json_seq
    application_prs_implied_object_yaml
    application_prs_implied_structure
    application_prs_mayfile
    application_prs_nprend
    application_prs_plucker
    application_prs_rdf_xml_crypt
    application_prs_sclt
    application_prs_vcfbzip2
    application_prs_xsf_xml
    application_pskc_xml
    application_pvd_json
    application_rdf_xml
    application_roughtime_malfeasance_json
    application_roughtime_server_json
    application_route_apd_xml
    application_route_s_tsid_xml
    application_route_usd_xml
    application_qsig
    application_raptorfec
    application_rdap_json
    application_reginfo_xml
    application_relax_ng_compact_syntax
    application_remote_printing
    application_reputon_json
    application_resolve_response_jwt
    application_resource_lists_diff_xml
    application_resource_lists_xml
    application_rfc_xml
    application_riscos
    application_rlmi_xml
    application_rls_services_xml
    application_rpki_checklist
    application_rpki_ghostbusters
    application_rpki_manifest
    application_rpki_publication
    application_rpki_roa
    application_rpki_signed_tal
    application_rpki_updown
    application_rs_metadata_xml
    application_rtf
    application_rtploopback
    application_rtx
    application_samlassertion_xml
    application_samlmetadata_xml
    application_sarif_external_properties_json
    application_sarif_json
    application_sbe
    application_sbml_xml
    application_scaip_xml
    application_scim_json
    application_scitt_receipt_cose
    application_scitt_statement_cose
    application_scvp_cv_request
    application_scvp_cv_response
    application_scvp_vp_request
    application_scvp_vp_response
    application_sd_jwt
    application_sd_jwt_json
    application_sdf_json
    application_sdp
    application_secevent_jwt
    application_senml_etch_cbor
    application_senml_etch_json
    application_senml_exi
    application_senml_cbor
    application_senml_json
    application_senml_xml
    application_sensml_exi
    application_sensml_cbor
    application_sensml_json
    application_sensml_xml
    application_sep_exi
    application_sep_xml
    application_session_info
    application_set_payment
    application_set_payment_initiation
    application_set_registration
    application_set_registration_initiation
    application_sgml
    application_sgml_open_catalog
    application_shf_xml
    application_sieve
    application_simple_filter_xml
    application_simple_message_summary
    application_simple_symbol_container
    application_sipc
    application_slate
    application_smil
    application_smil_xml
    application_smpte336m
    application_soap_fastinfoset
    application_soap_xml
    application_sparql_query
    application_spdx_json
    application_sparql_results_xml
    application_spirits_event_xml
    application_sql
    application_srgs
    application_srgs_xml
    application_sru_xml
    application_sslkeylogfile
    application_ssml_xml
    application_st2110_41
    application_stix_json
    application_stratum
    application_suit_envelope_cose
    application_suit_report_cose
    application_swid_cbor
    application_swid_xml
    application_syslog_msg
    application_tamp_apex_update
    application_tamp_apex_update_confirm
    application_tamp_community_update
    application_tamp_community_update_confirm
    application_tamp_error
    application_tamp_sequence_adjust
    application_tamp_sequence_adjust_confirm
    application_tamp_status_query
    application_tamp_status_response
    application_tamp_update
    application_tamp_update_confirm
    application_taxii_json
    application_td_json
    application_teep_cbor
    application_tei_xml
    application_tetra_isi
    application_texinfo
    application_thraud_xml
    application_timestamp_query
    application_timestamp_reply
    application_timestamped_data
    application_tlsrpt_gzip
    application_tlsrpt_json
    application_tm_json
    application_tnauthlist
    application_toc_cbor
    application_token_introspection_jwt
    application_toml
    application_trickle_ice_sdpfrag
    application_trig
    application_trust_chain_json
    application_trust_mark_jwt
    application_trust_mark_delegation_jwt
    application_trust_mark_status_response_jwt
    application_ttml_xml
    application_tve_trigger
    application_tzif
    application_tzif_leap
    application_uccs_cbor
    application_ujcs_json
    application_ulpfec
    application_urc_grpsheet_xml
    application_urc_ressheet_xml
    application_urc_targetdesc_xml
    application_urc_uisocketdesc_xml
    application_v3c
    application_vc
    application_vc_cose
    application_vc_jwt
    application_vc_sd_jwt
    application_vcard_json
    application_vcard_xml
    application_vec_xml
    application_vec_package_gzip
    application_vec_package_zip
    application_vemmi
    application_vnd_1000minds_decision_model_xml
    application_vnd_1ob
    application_vnd_3gpp_5gnas
    application_vnd_3gpp_5gsa2x
    application_vnd_3gpp_5gsa2x_local_service_information
    application_vnd_3gpp_5gsv2x
    application_vnd_3gpp_5gsv2x_local_service_information
    application_vnd_3gpp_access_transfer_events_xml
    application_vnd_3gpp_bsf_xml
    application_vnd_3gpp_crs_xml
    application_vnd_3gpp_current_location_discovery_xml
    application_vnd_3gpp_gmop_xml
    application_vnd_3gpp_gtpc
    application_vnd_3gpp_interworking_data
    application_vnd_3gpp_lpp
    application_vnd_3gpp_mc_signalling_ear
    application_vnd_3gpp_mcdata_affiliation_command_xml
    application_vnd_3gpp_mcdata_info_xml
    application_vnd_3gpp_mcdata_msgstore_ctrl_request_xml
    application_vnd_3gpp_mcdata_payload
    application_vnd_3gpp_mcdata_regroup_xml
    application_vnd_3gpp_mcdata_service_config_xml
    application_vnd_3gpp_mcdata_signalling
    application_vnd_3gpp_mcdata_ue_config_xml
    application_vnd_3gpp_mcdata_user_profile_xml
    application_vnd_3gpp_mcptt_affiliation_command_xml
    application_vnd_3gpp_mcptt_floor_request_xml
    application_vnd_3gpp_mcptt_info_xml
    application_vnd_3gpp_mcptt_location_info_xml
    application_vnd_3gpp_mcptt_mbms_usage_info_xml
    application_vnd_3gpp_mcptt_regroup_xml
    application_vnd_3gpp_mcptt_service_config_xml
    application_vnd_3gpp_mcptt_signed_xml
    application_vnd_3gpp_mcptt_ue_config_xml
    application_vnd_3gpp_mcptt_ue_init_config_xml
    application_vnd_3gpp_mcptt_user_profile_xml
    application_vnd_3gpp_mcs_location_user_config_xml
    application_vnd_3gpp_mcvideo_affiliation_command_xml
    application_vnd_3gpp_mcvideo_affiliation_info_xml
    application_vnd_3gpp_mcvideo_info_xml
    application_vnd_3gpp_mcvideo_location_info_xml
    application_vnd_3gpp_mcvideo_mbms_usage_info_xml
    application_vnd_3gpp_mcvideo_regroup_xml
    application_vnd_3gpp_mcvideo_service_config_xml
    application_vnd_3gpp_mcvideo_transmission_request_xml
    application_vnd_3gpp_mcvideo_ue_config_xml
    application_vnd_3gpp_mcvideo_user_profile_xml
    application_vnd_3gpp_mid_call_xml
    application_vnd_3gpp_ngap
    application_vnd_3gpp_pfcp
    application_vnd_3gpp_pic_bw_large
    application_vnd_3gpp_pic_bw_small
    application_vnd_3gpp_pic_bw_var
    application_vnd_3gpp_pinapp_info_xml
    application_vnd_3gpp_prose_pc3a_xml
    application_vnd_3gpp_prose_pc3ach_xml
    application_vnd_3gpp_prose_pc3ch_xml
    application_vnd_3gpp_prose_pc8_xml
    application_vnd_3gpp_prose_xml
    application_vnd_3gpp_s1ap
    application_vnd_3gpp_seal_app_comm_requirements_info_xml
    application_vnd_3gpp_seal_data_delivery_info_cbor
    application_vnd_3gpp_seal_data_delivery_info_xml
    application_vnd_3gpp_seal_group_doc_xml
    application_vnd_3gpp_seal_info_xml
    application_vnd_3gpp_seal_location_info_cbor
    application_vnd_3gpp_seal_location_info_xml
    application_vnd_3gpp_seal_mbms_usage_info_xml
    application_vnd_3gpp_seal_mbs_usage_info_xml
    application_vnd_3gpp_seal_network_qo_s_management_info_xml
    application_vnd_3gpp_seal_network_resource_info_cbor
    application_vnd_3gpp_seal_ue_config_info_xml
    application_vnd_3gpp_seal_unicast_info_xml
    application_vnd_3gpp_seal_user_profile_info_xml
    application_vnd_3gpp_sms
    application_vnd_3gpp_sms_xml
    application_vnd_3gpp_srvcc_ext_xml
    application_vnd_3gpp_srvcc_info_xml
    application_vnd_3gpp_state_and_event_info_xml
    application_vnd_3gpp_ussd_xml
    application_vnd_3gpp_vae_info_xml
    application_vnd_3gpp_v2x_local_service_information
    application_vnd_3gpp2_bcmcsinfo_xml
    application_vnd_3gpp2_sms
    application_vnd_3gpp2_tcap
    application_vnd_3gpp_v2x
    application_vnd_3lightssoftware_imagescal
    application_vnd_3_m_post_it_notes
    application_vnd_accpac_simply_aso
    application_vnd_accpac_simply_imp
    application_vnd_acm_addressxfer_json
    application_vnd_acm_chatbot_json
    application_vnd_acucobol
    application_vnd_acucorp
    application_vnd_adobe_flash_movie
    application_vnd_adobe_formscentral_fcdt
    application_vnd_adobe_fxp
    application_vnd_adobe_partial_upload
    application_vnd_adobe_xdp_xml
    application_vnd_aether_imp
    application_vnd_afpc_afplinedata
    application_vnd_afpc_afplinedata_pagedef
    application_vnd_afpc_cmoca_cmresource
    application_vnd_afpc_foca_charset
    application_vnd_afpc_foca_codedfont
    application_vnd_afpc_foca_codepage
    application_vnd_afpc_modca
    application_vnd_afpc_modca_cmtable
    application_vnd_afpc_modca_formdef
    application_vnd_afpc_modca_mediummap
    application_vnd_afpc_modca_objectcontainer
    application_vnd_afpc_modca_overlay
    application_vnd_afpc_modca_pagesegment
    application_vnd_age
    application_vnd_ah_barcode
    application_vnd_ahead_space
    application_vnd_aia
    application_vnd_airzip_filesecure_azf
    application_vnd_airzip_filesecure_azs
    application_vnd_amadeus_json
    application_vnd_amazon_mobi8_ebook
    application_vnd_americandynamics_acc
    application_vnd_amiga_ami
    application_vnd_amundsen_maze_xml
    application_vnd_android_ota
    application_vnd_anki
    application_vnd_anser_web_certificate_issue_initiation
    application_vnd_antix_game_component
    application_vnd_apache_arrow_file
    application_vnd_apache_arrow_stream
    application_vnd_apache_parquet
    application_vnd_apache_thrift_binary
    application_vnd_apache_thrift_compact
    application_vnd_apache_thrift_json
    application_vnd_apexlang
    application_vnd_api_json
    application_vnd_aplextor_warrp_json
    application_vnd_apothekende_reservation_json
    application_vnd_apple_installer_xml
    application_vnd_apple_keynote
    application_vnd_apple_mpegurl
    application_vnd_apple_numbers
    application_vnd_apple_pages
    application_vnd_arastra_swi
    application_vnd_aristanetworks_swi
    application_vnd_artisan_json
    application_vnd_artsquare
    application_vnd_as207960_vas_config_jer
    application_vnd_as207960_vas_config_uper
    application_vnd_as207960_vas_tap_jer
    application_vnd_as207960_vas_tap_uper
    application_vnd_astraea_software_iota
    application_vnd_audiograph
    application_vnd_autopackage
    application_vnd_avalon_json
    application_vnd_avistar_xml
    application_vnd_balsamiq_bmml_xml
    application_vnd_banana_accounting
    application_vnd_bbf_usp_error
    application_vnd_bbf_usp_msg
    application_vnd_bbf_usp_msg_json
    application_vnd_balsamiq_bmpr
    application_vnd_bekitzur_stech_json
    application_vnd_belightsoft_lhzd_zip
    application_vnd_belightsoft_lhzl_zip
    application_vnd_bint_med_content
    application_vnd_biopax_rdf_xml
    application_vnd_blink_idb_value_wrapper
    application_vnd_blueice_multipass
    application_vnd_bluetooth_ep_oob
    application_vnd_bluetooth_le_oob
    application_vnd_bmi
    application_vnd_bpf
    application_vnd_bpf3
    application_vnd_businessobjects
    application_vnd_byu_uapi_json
    application_vnd_bzip3
    application_vnd_c3voc_schedule_xml
    application_vnd_cab_jscript
    application_vnd_canon_cpdl
    application_vnd_canon_lips
    application_vnd_capasystems_pg_json
    application_vnd_cel
    application_vnd_cendio_thinlinc_clientconf
    application_vnd_century_systems_tcp_stream
    application_vnd_chemdraw_xml
    application_vnd_chess_pgn
    application_vnd_chipnuts_karaoke_mmd
    application_vnd_ciedi
    application_vnd_cinderella
    application_vnd_cirpack_isdn_ext
    application_vnd_citationstyles_style_xml
    application_vnd_claymore
    application_vnd_cloanto_rp9
    application_vnd_clonk_c4group
    application_vnd_cluetrust_cartomobile_config
    application_vnd_cluetrust_cartomobile_config_pkg
    application_vnd_cmmf_configuration_information_json
    application_vnd_cmmf_efd_xml
    application_vnd_cmmf_encoder_configuration_json
    application_vnd_cncf_helm_chart_content_v1_tar_gzip
    application_vnd_cncf_helm_chart_provenance_v1_prov
    application_vnd_cncf_helm_config_v1_json
    application_vnd_coffeescript
    application_vnd_collabio_xodocuments_document
    application_vnd_collabio_xodocuments_document_template
    application_vnd_collabio_xodocuments_presentation
    application_vnd_collabio_xodocuments_presentation_template
    application_vnd_collabio_xodocuments_spreadsheet
    application_vnd_collabio_xodocuments_spreadsheet_template
    application_vnd_collection_doc_json
    application_vnd_collection_json
    application_vnd_collection_next_json
    application_vnd_comicbook_rar
    application_vnd_comicbook_zip
    application_vnd_commerce_battelle
    application_vnd_commonspace
    application_vnd_coreos_ignition_json
    application_vnd_cosmocaller
    application_vnd_contact_cmsg
    application_vnd_crick_clicker
    application_vnd_crick_clicker_keyboard
    application_vnd_crick_clicker_palette
    application_vnd_crick_clicker_template
    application_vnd_crick_clicker_wordbank
    application_vnd_criticaltools_wbs_xml
    application_vnd_cryptii_pipe_json
    application_vnd_crypto_shade_file
    application_vnd_cryptomator_encrypted
    application_vnd_cryptomator_vault
    application_vnd_ctc_posml
    application_vnd_ctct_ws_xml
    application_vnd_cups_pdf
    application_vnd_cups_postscript
    application_vnd_cups_ppd
    application_vnd_cups_raster
    application_vnd_cups_raw
    application_vnd_curl
    application_vnd_cyan_dean_root_xml
    application_vnd_cybank
    application_vnd_cyclonedx_json
    application_vnd_cyclonedx_xml
    application_vnd_d2l_coursepackage1p0_zip
    application_vnd_d3m_dataset
    application_vnd_d3m_problem
    application_vnd_dart
    application_vnd_data_vision_rdz
    application_vnd_datalog
    application_vnd_datapackage_json
    application_vnd_dataresource_json
    application_vnd_dbf
    application_vnd_dcmp_xml
    application_vnd_debian_binary_package
    application_vnd_dece_data
    application_vnd_dece_ttml_xml
    application_vnd_dece_unspecified
    application_vnd_dece_zip
    application_vnd_denovo_fcselayout_link
    application_vnd_desmume_movie
    application_vnd_deut_json
    application_vnd_digitalstack_document_zip
    application_vnd_dir_bi_plate_dl_nosuffix
    application_vnd_dm_delegation_xml
    application_vnd_dna
    application_vnd_document_json
    application_vnd_dolby_mobile_1
    application_vnd_dolby_mobile_2
    application_vnd_doremir_scorecloud_binary_document
    application_vnd_dpgraph
    application_vnd_dreamfactory
    application_vnd_drive_json
    application_vnd_dtg_local
    application_vnd_dtg_local_flash
    application_vnd_dtg_local_html
    application_vnd_dvb_ait
    application_vnd_dvb_dvbisl_xml
    application_vnd_dvb_dvbj
    application_vnd_dvb_esgcontainer
    application_vnd_dvb_ipdcdftnotifaccess
    application_vnd_dvb_ipdcesgaccess
    application_vnd_dvb_ipdcesgaccess2
    application_vnd_dvb_ipdcesgpdd
    application_vnd_dvb_ipdcroaming
    application_vnd_dvb_iptv_alfec_base
    application_vnd_dvb_iptv_alfec_enhancement
    application_vnd_dvb_notif_aggregate_root_xml
    application_vnd_dvb_notif_container_xml
    application_vnd_dvb_notif_generic_xml
    application_vnd_dvb_notif_ia_msglist_xml
    application_vnd_dvb_notif_ia_registration_request_xml
    application_vnd_dvb_notif_ia_registration_response_xml
    application_vnd_dvb_notif_init_xml
    application_vnd_dvb_pfr
    application_vnd_dvb_service
    application_vnd_dxr
    application_vnd_dynageo
    application_vnd_dzr
    application_vnd_easykaraoke_cdgdownload
    application_vnd_ecip_rlp
    application_vnd_edulith_edux_json
    application_vnd_ecdis_update
    application_vnd_eclipse_ditto_json
    application_vnd_ecowin_chart
    application_vnd_ecowin_filerequest
    application_vnd_ecowin_fileupdate
    application_vnd_ecowin_series
    application_vnd_ecowin_seriesrequest
    application_vnd_ecowin_seriesupdate
    application_vnd_efi_img
    application_vnd_efi_iso
    application_vnd_eln_zip
    application_vnd_emclient_accessrequest_xml
    application_vnd_enliven
    application_vnd_enphase_envoy
    application_vnd_eprints_data_xml
    application_vnd_epson_esf
    application_vnd_epson_msf
    application_vnd_epson_quickanime
    application_vnd_epson_salt
    application_vnd_epson_ssf
    application_vnd_ericsson_quickcall
    application_vnd_erofs
    application_vnd_espass_espass_zip
    application_vnd_eszigno3_xml
    application_vnd_etsi_aoc_xml
    application_vnd_etsi_asic_s_zip
    application_vnd_etsi_asic_e_zip
    application_vnd_etsi_cug_xml
    application_vnd_etsi_iptvcommand_xml
    application_vnd_etsi_iptvdiscovery_xml
    application_vnd_etsi_iptvprofile_xml
    application_vnd_etsi_iptvsad_bc_xml
    application_vnd_etsi_iptvsad_cod_xml
    application_vnd_etsi_iptvsad_npvr_xml
    application_vnd_etsi_iptvservice_xml
    application_vnd_etsi_iptvsync_xml
    application_vnd_etsi_iptvueprofile_xml
    application_vnd_etsi_mcid_xml
    application_vnd_etsi_mheg5
    application_vnd_etsi_overload_control_policy_dataset_xml
    application_vnd_etsi_pstn_xml
    application_vnd_etsi_sci_xml
    application_vnd_etsi_simservs_xml
    application_vnd_etsi_timestamp_token
    application_vnd_etsi_tsl_xml
    application_vnd_etsi_tsl_der
    application_vnd_eu_kasparian_car_json
    application_vnd_eudora_data
    application_vnd_evolv_ecig_profile
    application_vnd_evolv_ecig_settings
    application_vnd_evolv_ecig_theme
    application_vnd_exstream_empower_zip
    application_vnd_exstream_package
    application_vnd_ezpix_album
    application_vnd_ezpix_package
    application_vnd_f_secure_mobile
    application_vnd_faf_yaml
    application_vnd_fastcopy_disk_image
    application_vnd_familysearch_gedcom_zip
    application_vnd_fdsn_mseed
    application_vnd_fdsn_seed
    application_vnd_fdsn_stationxml_xml
    application_vnd_ffsns
    application_vnd_fgb
    application_vnd_ficlab_flb_zip
    application_vnd_filmit_zfc
    application_vnd_fints
    application_vnd_firemonkeys_cloudcell
    application_vnd_flo_graph_it
    application_vnd_fluxtime_clip
    application_vnd_font_fontforge_sfd
    application_vnd_foritech_container
    application_vnd_framemaker
    application_vnd_freelog_comic
    application_vnd_frogans_fnc
    application_vnd_frogans_ltf
    application_vnd_fsc_weblaunch
    application_vnd_fujifilm_fb_docuworks
    application_vnd_fujifilm_fb_docuworks_binder
    application_vnd_fujifilm_fb_docuworks_container
    application_vnd_fujifilm_fb_jfi_xml
    application_vnd_fujitsu_oasys
    application_vnd_fujitsu_oasys2
    application_vnd_fujitsu_oasys3
    application_vnd_fujitsu_oasysgp
    application_vnd_fujitsu_oasysprs
    application_vnd_fujixerox_art4
    application_vnd_fujixerox_art_ex
    application_vnd_fujixerox_ddd
    application_vnd_fujixerox_docuworks
    application_vnd_fujixerox_docuworks_binder
    application_vnd_fujixerox_docuworks_container
    application_vnd_fujixerox_hbpl
    application_vnd_fut_misnet
    application_vnd_futoin_cbor
    application_vnd_futoin_json
    application_vnd_fuzzysheet
    application_vnd_g3pix_g3fc
    application_vnd_ga4gh_passport_jwt
    application_vnd_genomatix_tuxedo
    application_vnd_genozip
    application_vnd_gentics_grd_json
    application_vnd_gentoo_catmetadata_xml
    application_vnd_gentoo_ebuild
    application_vnd_gentoo_eclass
    application_vnd_gentoo_gpkg
    application_vnd_gentoo_manifest
    application_vnd_gentoo_xpak
    application_vnd_gentoo_pkgmetadata_xml
    application_vnd_geo_json
    application_vnd_geocube_xml
    application_vnd_geogebra_file
    application_vnd_geogebra_pinboard
    application_vnd_geogebra_slides
    application_vnd_geogebra_tool
    application_vnd_geometry_explorer
    application_vnd_geonext
    application_vnd_geoplan
    application_vnd_geospace
    application_vnd_gerber
    application_vnd_globalplatform_card_content_mgt
    application_vnd_globalplatform_card_content_mgt_response
    application_vnd_gmx
    application_vnd_gnu_taler_exchange_json
    application_vnd_gnu_taler_merchant_json
    application_vnd_google_earth_kml_xml
    application_vnd_google_earth_kmz
    application_vnd_gov_sk_e_form_xml
    application_vnd_gov_sk_e_form_zip
    application_vnd_gov_sk_xmldatacontainer_xml
    application_vnd_gp3
    application_vnd_gpxsee_map_xml
    application_vnd_grafeq
    application_vnd_gridmp
    application_vnd_groove_account
    application_vnd_groove_help
    application_vnd_groove_identity_message
    application_vnd_groove_injector
    application_vnd_groove_tool_message
    application_vnd_groove_tool_template
    application_vnd_groove_vcard
    application_vnd_hal_json
    application_vnd_hal_xml
    application_vnd_hand_held_entertainment_xml
    application_vnd_hbci
    application_vnd_hc_json
    application_vnd_hcl_bireports
    application_vnd_hdfgroup_hdf4
    application_vnd_hdfgroup_hdf5
    application_vnd_hdt
    application_vnd_heroku_json
    application_vnd_hhe_lesson_player
    application_vnd_hp_hpgl
    application_vnd_hp_hpid
    application_vnd_hp_hps
    application_vnd_hp_jlyt
    application_vnd_hp_pcl
    application_vnd_hp_pclxl
    application_vnd_hsl
    application_vnd_httphone
    application_vnd_hydrostatix_sof_data
    application_vnd_hyper_item_json
    application_vnd_hyper_json
    application_vnd_hyperdrive_json
    application_vnd_hzn_3d_crossword
    application_vnd_ibm_afplinedata
    application_vnd_ibm_electronic_media
    application_vnd_ibm_mini_pay
    application_vnd_ibm_modcap
    application_vnd_ibm_rights_management
    application_vnd_ibm_secure_container
    application_vnd_iccprofile
    application_vnd_ieee_1905
    application_vnd_igloader
    application_vnd_imagemeter_folder_zip
    application_vnd_imagemeter_image_zip
    application_vnd_immervision_ivp
    application_vnd_immervision_ivu
    application_vnd_ims_imsccv1p1
    application_vnd_ims_imsccv1p2
    application_vnd_ims_imsccv1p3
    application_vnd_ims_lis_v2_result_json
    application_vnd_ims_lti_v2_toolconsumerprofile_json
    application_vnd_ims_lti_v2_toolproxy_id_json
    application_vnd_ims_lti_v2_toolproxy_json
    application_vnd_ims_lti_v2_toolsettings_json
    application_vnd_ims_lti_v2_toolsettings_simple_json
    application_vnd_informedcontrol_rms_xml
    application_vnd_infotech_project
    application_vnd_infotech_project_xml
    application_vnd_informix_visionary
    application_vnd_innopath_wamp_notification
    application_vnd_insors_igm
    application_vnd_intercon_formnet
    application_vnd_intergeo
    application_vnd_intertrust_digibox
    application_vnd_intertrust_nncp
    application_vnd_intu_qbo
    application_vnd_intu_qfx
    application_vnd_ipfs_ipns_record
    application_vnd_ipld_car
    application_vnd_ipld_dag_cbor
    application_vnd_ipld_dag_json
    application_vnd_ipld_raw
    application_vnd_iptc_g2_catalogitem_xml
    application_vnd_iptc_g2_conceptitem_xml
    application_vnd_iptc_g2_knowledgeitem_xml
    application_vnd_iptc_g2_newsitem_xml
    application_vnd_iptc_g2_newsmessage_xml
    application_vnd_iptc_g2_packageitem_xml
    application_vnd_iptc_g2_planningitem_xml
    application_vnd_ipunplugged_rcprofile
    application_vnd_irepository_package_xml
    application_vnd_is_xpr
    application_vnd_isac_fcs
    application_vnd_jam
    application_vnd_iso11783_10_zip
    application_vnd_japannet_directory_service
    application_vnd_japannet_jpnstore_wakeup
    application_vnd_japannet_payment_wakeup
    application_vnd_japannet_registration
    application_vnd_japannet_registration_wakeup
    application_vnd_japannet_setstore_wakeup
    application_vnd_japannet_verification
    application_vnd_japannet_verification_wakeup
    application_vnd_jcp_javame_midlet_rms
    application_vnd_jisp
    application_vnd_joost_joda_archive
    application_vnd_jsk_isdn_ngn
    application_vnd_kahootz
    application_vnd_kde_karbon
    application_vnd_kde_kchart
    application_vnd_kde_kformula
    application_vnd_kde_kivio
    application_vnd_kde_kontour
    application_vnd_kde_kpresenter
    application_vnd_kde_kspread
    application_vnd_kde_kword
    application_vnd_kdl
    application_vnd_kenameaapp
    application_vnd_keyman_kmp_zip
    application_vnd_keyman_kmx
    application_vnd_kidspiration
    application_vnd_kinar
    application_vnd_koan
    application_vnd_kodak_descriptor
    application_vnd_las
    application_vnd_las_las_json
    application_vnd_las_las_xml
    application_vnd_laszip
    application_vnd_ldev_productlicensing
    application_vnd_leap_json
    application_vnd_liberty_request_xml
    application_vnd_llamagraphics_life_balance_desktop
    application_vnd_llamagraphics_life_balance_exchange_xml
    application_vnd_logipipe_circuit_zip
    application_vnd_loom
    application_vnd_lotus_1_2_3
    application_vnd_lotus_approach
    application_vnd_lotus_freelance
    application_vnd_lotus_notes
    application_vnd_lotus_organizer
    application_vnd_lotus_screencam
    application_vnd_lotus_wordpro
    application_vnd_lukuid_package_zip
    application_vnd_macports_portpkg
    application_vnd_majikah_bundle
    application_vnd_maml
    application_vnd_mapbox_vector_tile
    application_vnd_marlin_drm_actiontoken_xml
    application_vnd_marlin_drm_conftoken_xml
    application_vnd_marlin_drm_license_xml
    application_vnd_marlin_drm_mdcf
    application_vnd_mason_json
    application_vnd_maxar_archive_3tz_zip
    application_vnd_maxmind_maxmind_db
    application_vnd_mcd
    application_vnd_mdl
    application_vnd_mdl_mbsdf
    application_vnd_medcalcdata
    application_vnd_mediastation_cdkey
    application_vnd_medicalholodeck_recordxr
    application_vnd_meridian_slingshot
    application_vnd_mermaid
    application_vnd_mfer
    application_vnd_mfmp
    application_vnd_micro_json
    application_vnd_micrografx_flo
    application_vnd_micrografx_igx
    application_vnd_microsoft_portable_executable
    application_vnd_microsoft_windows_thumbnail_cache
    application_vnd_miele_json
    application_vnd_mif
    application_vnd_minisoft_hp3000_save
    application_vnd_mitsubishi_misty_guard_trustweb
    application_vnd_mobius_daf
    application_vnd_mobius_dis
    application_vnd_mobius_mbk
    application_vnd_mobius_mqy
    application_vnd_mobius_msl
    application_vnd_mobius_plc
    application_vnd_mobius_txf
    application_vnd_modl
    application_vnd_mophun_application
    application_vnd_mophun_certificate
    application_vnd_motorola_flexsuite
    application_vnd_motorola_flexsuite_adsi
    application_vnd_motorola_flexsuite_fis
    application_vnd_motorola_flexsuite_gotap
    application_vnd_motorola_flexsuite_kmr
    application_vnd_motorola_flexsuite_ttc
    application_vnd_motorola_flexsuite_wem
    application_vnd_motorola_iprm
    application_vnd_mozilla_xul_xml
    application_vnd_ms_artgalry
    application_vnd_ms_asf
    application_vnd_ms_cab_compressed
    application_vnd_ms_3mfdocument
    application_vnd_ms_excel
    application_vnd_ms_excel_addin_macro_enabled_12
    application_vnd_ms_excel_sheet_binary_macro_enabled_12
    application_vnd_ms_excel_sheet_macro_enabled_12
    application_vnd_ms_excel_template_macro_enabled_12
    application_vnd_ms_fontobject
    application_vnd_ms_htmlhelp
    application_vnd_ms_ims
    application_vnd_ms_lrm
    application_vnd_ms_office_active_x_xml
    application_vnd_ms_officetheme
    application_vnd_ms_playready_initiator_xml
    application_vnd_ms_powerpoint
    application_vnd_ms_powerpoint_addin_macro_enabled_12
    application_vnd_ms_powerpoint_presentation_macro_enabled_12
    application_vnd_ms_powerpoint_slide_macro_enabled_12
    application_vnd_ms_powerpoint_slideshow_macro_enabled_12
    application_vnd_ms_powerpoint_template_macro_enabled_12
    application_vnd_ms_print_device_capabilities_xml
    application_vnd_ms_print_schema_ticket_xml
    application_vnd_ms_project
    application_vnd_ms_tnef
    application_vnd_ms_windows_devicepairing
    application_vnd_ms_windows_nwprinting_oob
    application_vnd_ms_windows_printerpairing
    application_vnd_ms_windows_wsd_oob
    application_vnd_ms_wmdrm_lic_chlg_req
    application_vnd_ms_wmdrm_lic_resp
    application_vnd_ms_wmdrm_meter_chlg_req
    application_vnd_ms_wmdrm_meter_resp
    application_vnd_ms_word_document_macro_enabled_12
    application_vnd_ms_word_template_macro_enabled_12
    application_vnd_ms_works
    application_vnd_ms_wpl
    application_vnd_ms_xpsdocument
    application_vnd_msa_disk_image
    application_vnd_mseq
    application_vnd_msgpack
    application_vnd_msign
    application_vnd_multiad_creator
    application_vnd_multiad_creator_cif
    application_vnd_musician
    application_vnd_music_niff
    application_vnd_muvee_style
    application_vnd_mynfc
    application_vnd_nacamar_ybrid_json
    application_vnd_nato_bindingdataobject_cbor
    application_vnd_nato_bindingdataobject_json
    application_vnd_nato_bindingdataobject_xml
    application_vnd_nato_openxmlformats_package_iepd_zip
    application_vnd_ncd_control
    application_vnd_ncd_reference
    application_vnd_nearst_inv_json
    application_vnd_nebumind_line
    application_vnd_nervana
    application_vnd_netfpx
    application_vnd_neurolanguage_nlu
    application_vnd_nila_protobuf_bundle_zip
    application_vnd_nimn
    application_vnd_nintendo_snes_rom
    application_vnd_nintendo_nitro_rom
    application_vnd_nitf
    application_vnd_noblenet_directory
    application_vnd_noblenet_sealer
    application_vnd_noblenet_web
    application_vnd_nokia_catalogs
    application_vnd_nokia_conml_wbxml
    application_vnd_nokia_conml_xml
    application_vnd_nokia_iptv_config_xml
    application_vnd_nokia_i_sds_radio_presets
    application_vnd_nokia_landmark_wbxml
    application_vnd_nokia_landmark_xml
    application_vnd_nokia_landmarkcollection_xml
    application_vnd_nokia_ncd
    application_vnd_nokia_n_gage_ac_xml
    application_vnd_nokia_n_gage_data
    application_vnd_nokia_n_gage_symbian_install
    application_vnd_nokia_pcd_wbxml
    application_vnd_nokia_pcd_xml
    application_vnd_nokia_radio_preset
    application_vnd_nokia_radio_presets
    application_vnd_novadigm_edm
    application_vnd_novadigm_edx
    application_vnd_novadigm_ext
    application_vnd_ntt_local_content_share
    application_vnd_ntt_local_file_transfer
    application_vnd_ntt_local_ogw_remote_access
    application_vnd_ntt_local_sip_ta_remote
    application_vnd_ntt_local_sip_ta_tcp_stream
    application_vnd_nubaltec_nudoku_game
    application_vnd_oai_workflows
    application_vnd_oai_workflows_json
    application_vnd_oai_workflows_yaml
    application_vnd_oasis_opendocument_base
    application_vnd_oasis_opendocument_chart
    application_vnd_oasis_opendocument_chart_template
    application_vnd_oasis_opendocument_database
    application_vnd_oasis_opendocument_formula
    application_vnd_oasis_opendocument_formula_template
    application_vnd_oasis_opendocument_graphics
    application_vnd_oasis_opendocument_graphics_template
    application_vnd_oasis_opendocument_image
    application_vnd_oasis_opendocument_image_template
    application_vnd_oasis_opendocument_presentation
    application_vnd_oasis_opendocument_presentation_template
    application_vnd_oasis_opendocument_spreadsheet
    application_vnd_oasis_opendocument_spreadsheet_template
    application_vnd_oasis_opendocument_text
    application_vnd_oasis_opendocument_text_master
    application_vnd_oasis_opendocument_text_master_template
    application_vnd_oasis_opendocument_text_template
    application_vnd_oasis_opendocument_text_web
    application_vnd_obn
    application_vnd_ocf_cbor
    application_vnd_oci_image_manifest_v1_json
    application_vnd_oftn_l10n_json
    application_vnd_oipf_contentaccessdownload_xml
    application_vnd_oipf_contentaccessstreaming_xml
    application_vnd_oipf_cspg_hexbinary
    application_vnd_oipf_dae_svg_xml
    application_vnd_oipf_dae_xhtml_xml
    application_vnd_oipf_mippvcontrolmessage_xml
    application_vnd_oipf_pae_gem
    application_vnd_oipf_spdiscovery_xml
    application_vnd_oipf_spdlist_xml
    application_vnd_oipf_ueprofile_xml
    application_vnd_oipf_userprofile_xml
    application_vnd_olpc_sugar
    application_vnd_oma_bcast_associated_procedure_parameter_xml
    application_vnd_oma_bcast_drm_trigger_xml
    application_vnd_oma_bcast_imd_xml
    application_vnd_oma_bcast_ltkm
    application_vnd_oma_bcast_notification_xml
    application_vnd_oma_bcast_provisioningtrigger
    application_vnd_oma_bcast_sgboot
    application_vnd_oma_bcast_sgdd_xml
    application_vnd_oma_bcast_sgdu
    application_vnd_oma_bcast_simple_symbol_container
    application_vnd_oma_bcast_smartcard_trigger_xml
    application_vnd_oma_bcast_sprov_xml
    application_vnd_oma_bcast_stkm
    application_vnd_oma_cab_address_book_xml
    application_vnd_oma_cab_feature_handler_xml
    application_vnd_oma_cab_pcc_xml
    application_vnd_oma_cab_subs_invite_xml
    application_vnd_oma_cab_user_prefs_xml
    application_vnd_oma_dcd
    application_vnd_oma_dcdc
    application_vnd_oma_dd2_xml
    application_vnd_oma_drm_risd_xml
    application_vnd_oma_group_usage_list_xml
    application_vnd_oma_lwm2m_cbor
    application_vnd_oma_lwm2m_json
    application_vnd_oma_lwm2m_tlv
    application_vnd_oma_pal_xml
    application_vnd_oma_poc_detailed_progress_report_xml
    application_vnd_oma_poc_final_report_xml
    application_vnd_oma_poc_groups_xml
    application_vnd_oma_poc_invocation_descriptor_xml
    application_vnd_oma_poc_optimized_progress_report_xml
    application_vnd_oma_push
    application_vnd_oma_scidm_messages_xml
    application_vnd_oma_xcap_directory_xml
    application_vnd_omads_email_xml
    application_vnd_omads_file_xml
    application_vnd_omads_folder_xml
    application_vnd_omaloc_supl_init
    application_vnd_oma_scws_config
    application_vnd_oma_scws_http_request
    application_vnd_oma_scws_http_response
    application_vnd_oms_cellular_cose_content_cbor
    application_vnd_onepager
    application_vnd_onepagertamp
    application_vnd_onepagertamx
    application_vnd_onepagertat
    application_vnd_onepagertatp
    application_vnd_onepagertatx
    application_vnd_onvif_metadata
    application_vnd_openblox_game_binary
    application_vnd_openblox_game_xml
    application_vnd_openeye_oeb
    application_vnd_openprinttag
    application_vnd_openstreetmap_data_xml
    application_vnd_opentimestamps_ots
    application_vnd_openvpi_dspx_json
    application_vnd_openxmlformats_officedocument_custom_properties_xml
    application_vnd_openxmlformats_officedocument_custom_xml_properties_xml
    application_vnd_openxmlformats_officedocument_drawing_xml
    application_vnd_openxmlformats_officedocument_drawingml_chart_xml
    application_vnd_openxmlformats_officedocument_drawingml_chartshapes_xml
    application_vnd_openxmlformats_officedocument_drawingml_diagram_colors_xml
    application_vnd_openxmlformats_officedocument_drawingml_diagram_data_xml
    application_vnd_openxmlformats_officedocument_drawingml_diagram_layout_xml
    application_vnd_openxmlformats_officedocument_drawingml_diagram_style_xml
    application_vnd_openxmlformats_officedocument_extended_properties_xml
    application_vnd_openxmlformats_officedocument_presentationml_comment_authors_xml
    application_vnd_openxmlformats_officedocument_presentationml_comments_xml
    application_vnd_openxmlformats_officedocument_presentationml_handout_master_xml
    application_vnd_openxmlformats_officedocument_presentationml_notes_master_xml
    application_vnd_openxmlformats_officedocument_presentationml_notes_slide_xml
    application_vnd_openxmlformats_officedocument_presentationml_presentation
    application_vnd_openxmlformats_officedocument_presentationml_presentation_main_xml
    application_vnd_openxmlformats_officedocument_presentationml_pres_props_xml
    application_vnd_openxmlformats_officedocument_presentationml_slide
    application_vnd_openxmlformats_officedocument_presentationml_slide_xml
    application_vnd_openxmlformats_officedocument_presentationml_slide_layout_xml
    application_vnd_openxmlformats_officedocument_presentationml_slide_master_xml
    application_vnd_openxmlformats_officedocument_presentationml_slideshow
    application_vnd_openxmlformats_officedocument_presentationml_slideshow_main_xml
    application_vnd_openxmlformats_officedocument_presentationml_slide_update_info_xml
    application_vnd_openxmlformats_officedocument_presentationml_table_styles_xml
    application_vnd_openxmlformats_officedocument_presentationml_tags_xml
    application_vnd_openxmlformats_officedocument_presentationml_template
    application_vnd_openxmlformats_officedocument_presentationml_template_main_xml
    application_vnd_openxmlformats_officedocument_presentationml_view_props_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_calc_chain_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_chartsheet_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_comments_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_connections_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_dialogsheet_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_external_link_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_pivot_cache_definition_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_pivot_cache_records_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_pivot_table_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_query_table_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_revision_headers_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_revision_log_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_shared_strings_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_sheet
    application_vnd_openxmlformats_officedocument_spreadsheetml_sheet_main_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_sheet_metadata_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_styles_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_table_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_table_single_cells_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_template
    application_vnd_openxmlformats_officedocument_spreadsheetml_template_main_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_user_names_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_volatile_dependencies_xml
    application_vnd_openxmlformats_officedocument_spreadsheetml_worksheet_xml
    application_vnd_openxmlformats_officedocument_theme_xml
    application_vnd_openxmlformats_officedocument_theme_override_xml
    application_vnd_openxmlformats_officedocument_vml_drawing
    application_vnd_openxmlformats_officedocument_wordprocessingml_comments_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_document
    application_vnd_openxmlformats_officedocument_wordprocessingml_document_glossary_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_document_main_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_endnotes_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_font_table_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_footer_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_footnotes_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_numbering_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_settings_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_styles_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_template
    application_vnd_openxmlformats_officedocument_wordprocessingml_template_main_xml
    application_vnd_openxmlformats_officedocument_wordprocessingml_web_settings_xml
    application_vnd_openxmlformats_package_core_properties_xml
    application_vnd_openxmlformats_package_digital_signature_xmlsignature_xml
    application_vnd_openxmlformats_package_relationships_xml
    application_vnd_oracle_resource_json
    application_vnd_orange_indata
    application_vnd_osa_netdeploy
    application_vnd_osgeo_mapguide_package
    application_vnd_osgi_bundle
    application_vnd_osgi_dp
    application_vnd_osgi_subsystem
    application_vnd_otps_ct_kip_xml
    application_vnd_oxli_countgraph
    application_vnd_pagerduty_json
    application_vnd_palm
    application_vnd_panoply
    application_vnd_paos_xml
    application_vnd_patentdive
    application_vnd_patientecommsdoc
    application_vnd_pawaafile
    application_vnd_pcos
    application_vnd_pg_format
    application_vnd_pg_osasli
    application_vnd_phbk_xml
    application_vnd_piaccess_application_licence
    application_vnd_picsel
    application_vnd_pmi_widget
    application_vnd_pmtiles
    application_vnd_poc_group_advertisement_xml
    application_vnd_pocketlearn
    application_vnd_powerbuilder6
    application_vnd_powerbuilder6_s
    application_vnd_powerbuilder7
    application_vnd_powerbuilder75
    application_vnd_powerbuilder75_s
    application_vnd_powerbuilder7_s
    application_vnd_pp_systemverify_xml
    application_vnd_preminet
    application_vnd_previewsystems_box
    application_vnd_project_graph
    application_vnd_proteus_magazine
    application_vnd_psfs
    application_vnd_pt_mundusmundi
    application_vnd_publishare_delta_tree
    application_vnd_pvi_ptid1
    application_vnd_pwg_multiplexed
    application_vnd_pwg_xhtml_print_xml
    application_vnd_pyon_json
    application_vnd_qualcomm_brew_app_res
    application_vnd_quarantainenet
    application_vnd_quark_quark_x_press
    application_vnd_quobject_quoxdocument
    application_vnd_r74n_sandboxels_json
    application_vnd_radisys_moml_xml
    application_vnd_radisys_msml_audit_conf_xml
    application_vnd_radisys_msml_audit_conn_xml
    application_vnd_radisys_msml_audit_dialog_xml
    application_vnd_radisys_msml_audit_stream_xml
    application_vnd_radisys_msml_audit_xml
    application_vnd_radisys_msml_conf_xml
    application_vnd_radisys_msml_dialog_base_xml
    application_vnd_radisys_msml_dialog_fax_detect_xml
    application_vnd_radisys_msml_dialog_fax_sendrecv_xml
    application_vnd_radisys_msml_dialog_group_xml
    application_vnd_radisys_msml_dialog_speech_xml
    application_vnd_radisys_msml_dialog_transform_xml
    application_vnd_radisys_msml_dialog_xml
    application_vnd_radisys_msml_xml
    application_vnd_rainstor_data
    application_vnd_rapid
    application_vnd_rar
    application_vnd_realvnc_bed
    application_vnd_recordare_musicxml
    application_vnd_recordare_musicxml_xml
    application_vnd_rego
    application_vnd_relpipe
    application_vnd_ren_learn_rlprint
    application_vnd_resilient_logic
    application_vnd_restful_json
    application_vnd_rig_cryptonote
    application_vnd_route66_link66_xml
    application_vnd_rs_274x
    application_vnd_ruckus_download
    application_vnd_s3sms
    application_vnd_sailingtracker_track
    application_vnd_sar
    application_vnd_sbm_cid
    application_vnd_sbm_mid2
    application_vnd_scribus
    application_vnd_sealed_3df
    application_vnd_sealed_csf
    application_vnd_sealed_doc
    application_vnd_sealed_eml
    application_vnd_sealed_mht
    application_vnd_sealed_net
    application_vnd_sealed_ppt
    application_vnd_sealed_tiff
    application_vnd_sealed_xls
    application_vnd_sealedmedia_softseal_html
    application_vnd_sealedmedia_softseal_pdf
    application_vnd_seemail
    application_vnd_seis_json
    application_vnd_sema
    application_vnd_semd
    application_vnd_semf
    application_vnd_shade_save_file
    application_vnd_shana_informed_formdata
    application_vnd_shana_informed_formtemplate
    application_vnd_shana_informed_interchange
    application_vnd_shana_informed_package
    application_vnd_shootproof_json
    application_vnd_shopkick_json
    application_vnd_shp
    application_vnd_shx
    application_vnd_sigrok_session
    application_vnd_sim_tech_mind_mapper
    application_vnd_siren_json
    application_vnd_sirtx_vmv0
    application_vnd_sketchometry
    application_vnd_smaf
    application_vnd_smart_notebook
    application_vnd_smart_teacher
    application_vnd_smintio_portals_archive
    application_vnd_snesdev_page_table
    application_vnd_software602_filler_form_xml
    application_vnd_software602_filler_form_xml_zip
    application_vnd_solent_sdkm_xml
    application_vnd_spotfire_dxp
    application_vnd_spotfire_sfs
    application_vnd_sqlite3
    application_vnd_sri
    application_vnd_sss_cod
    application_vnd_sss_dtf
    application_vnd_sss_ntf
    application_vnd_stepmania_package
    application_vnd_stepmania_stepchart
    application_vnd_street_stream
    application_vnd_sun_wadl_xml
    application_vnd_superfile_super
    application_vnd_sus_calendar
    application_vnd_svd
    application_vnd_swiftview_ics
    application_vnd_sybyl_mol2
    application_vnd_sycle_xml
    application_vnd_syft_json
    application_vnd_syncml_dm_notification
    application_vnd_syncml_dmddf_xml
    application_vnd_syncml_dmtnds_wbxml
    application_vnd_syncml_dmtnds_xml
    application_vnd_syncml_dmddf_wbxml
    application_vnd_syncml_dm_wbxml
    application_vnd_syncml_dm_xml
    application_vnd_syncml_ds_notification
    application_vnd_syncml_xml
    application_vnd_tableschema_json
    application_vnd_tao_intent_module_archive
    application_vnd_tcpdump_pcap
    application_vnd_think_cell_ppttc_json
    application_vnd_tml
    application_vnd_tmd_mediaflex_api_xml
    application_vnd_tmobile_livetv
    application_vnd_tri_onesource
    application_vnd_trid_tpt
    application_vnd_triscape_mxs
    application_vnd_trueapp
    application_vnd_truedoc
    application_vnd_ubisoft_webplayer
    application_vnd_ufdl
    application_vnd_uic_dosipas_v1
    application_vnd_uic_dosipas_v2
    application_vnd_uic_osdm_json
    application_vnd_uic_tlb_fcb
    application_vnd_uiq_theme
    application_vnd_umajin
    application_vnd_unity
    application_vnd_uoml_xml
    application_vnd_uplanet_alert
    application_vnd_uplanet_alert_wbxml
    application_vnd_uplanet_bearer_choice
    application_vnd_uplanet_bearer_choice_wbxml
    application_vnd_uplanet_cacheop
    application_vnd_uplanet_cacheop_wbxml
    application_vnd_uplanet_channel
    application_vnd_uplanet_channel_wbxml
    application_vnd_uplanet_list
    application_vnd_uplanet_listcmd
    application_vnd_uplanet_listcmd_wbxml
    application_vnd_uplanet_list_wbxml
    application_vnd_uri_map
    application_vnd_uplanet_signal
    application_vnd_valve_source_material
    application_vnd_vcx
    application_vnd_vd_study
    application_vnd_vectorworks
    application_vnd_vel_json
    application_vnd_veraison_tsm_report_cbor
    application_vnd_veraison_tsm_report_json
    application_vnd_verifier_attestation_jwt
    application_vnd_verimatrix_vcas
    application_vnd_veritone_aion_json
    application_vnd_vertifile_pvf
    application_vnd_veryant_thin
    application_vnd_ves_encrypted
    application_vnd_vidsoft_vidconference
    application_vnd_vimina_vma
    application_vnd_visio
    application_vnd_visionary
    application_vnd_vividence_scriptfile
    application_vnd_vocalshaper_vsp4
    application_vnd_vsf
    application_vnd_vuq
    application_vnd_wantverse
    application_vnd_wap_sic
    application_vnd_wap_slc
    application_vnd_wap_wbxml
    application_vnd_wap_wmlc
    application_vnd_wap_wmlscriptc
    application_vnd_wasmflow_wafl
    application_vnd_webturbo
    application_vnd_wfa_dpp
    application_vnd_wfa_p2p
    application_vnd_wfa_wsc
    application_vnd_windows_devicepairing
    application_vnd_wmap
    application_vnd_wmc
    application_vnd_wmf_bootstrap
    application_vnd_wolfram_mathematica
    application_vnd_wolfram_mathematica_package
    application_vnd_wolfram_player
    application_vnd_wordlift
    application_vnd_wordperfect
    application_vnd_wqd
    application_vnd_wrq_hp3000_labelled
    application_vnd_wt_stf
    application_vnd_wv_csp_xml
    application_vnd_wv_csp_wbxml
    application_vnd_wv_ssp_xml
    application_vnd_xacml_json
    application_vnd_xara
    application_vnd_xarin_cpj
    application_vnd_xcdn
    application_vnd_xecrets_encrypted
    application_vnd_xfdl
    application_vnd_xfdl_webform
    application_vnd_xmi_xml
    application_vnd_xmpie_cpkg
    application_vnd_xmpie_dpkg
    application_vnd_xmpie_plan
    application_vnd_xmpie_ppkg
    application_vnd_xmpie_xlim
    application_vnd_yamaha_hv_dic
    application_vnd_yamaha_hv_script
    application_vnd_yamaha_hv_voice
    application_vnd_yamaha_openscoreformat_osfpvg_xml
    application_vnd_yamaha_openscoreformat
    application_vnd_yamaha_remote_setup
    application_vnd_yamaha_smaf_audio
    application_vnd_yamaha_smaf_phrase
    application_vnd_yamaha_through_ngn
    application_vnd_yamaha_tunnel_udpencap
    application_vnd_yaoweme
    application_vnd_yellowriver_custom_menu
    application_vnd_youtube_yt
    application_vnd_zoho_document_writer
    application_vnd_zoho_presentation_show
    application_vnd_zoho_spreadsheetml_sheet
    application_vnd_zul
    application_vnd_zzazz_deck_xml
    application_voicexml_xml
    application_voucher_cms_json
    application_voucher_jws_json
    application_vp
    application_vp_cose
    application_vp_jwt
    application_vp_sd_jwt
    application_vq_rtcpxr
    application_wasm
    application_watcherinfo_xml
    application_webpush_options_json
    application_whoispp_query
    application_whoispp_response
    application_widget
    application_wita
    application_wordperfect5_1
    application_wsdl_xml
    application_wspolicy_xml
    application_x_pki_message
    application_x_www_form_urlencoded
    application_x_x509_ca_cert
    application_x_x509_ca_ra_cert
    application_x_x509_next_ca_cert
    application_x400_bp
    application_xacml_xml
    application_xcap_att_xml
    application_xcap_caps_xml
    application_xcap_diff_xml
    application_xcap_el_xml
    application_xcap_error_xml
    application_xcap_ns_xml
    application_xcon_conference_info_diff_xml
    application_xcon_conference_info_xml
    application_xenc_xml
    application_xfdf
    application_xhtml_xml
    application_xliff_xml
    application_xml
    application_xml_dtd
    application_xml_external_parsed_entity
    application_xml_patch_xml
    application_xmpp_xml
    application_xop_xml
    application_xslt_xml
    application_xv_xml
    application_yaml
    application_yang
    application_yang_data_cbor
    application_yang_data_json
    application_yang_data_xml
    application_yang_patch_json
    application_yang_patch_xml
    application_yang_sid_json
    application_yin_xml
    application_zip
    application_zlib
    application_zstd
    audio_1d_interleaved_parityfec
    audio_32kadpcm
    audio_3gpp
    audio_3gpp2
    audio_aac
    audio_ac3
    audio_amr
    audio_amr_wb
    audio_aptx
    audio_asc
    audio_atrac_advanced_lossless
    audio_atrac_x
    audio_atrac3
    audio_basic
    audio_bv16
    audio_bv32
    audio_clearmode
    audio_cn
    audio_dat12
    audio_dls
    audio_dsr_es201108
    audio_dsr_es202050
    audio_dsr_es202211
    audio_dsr_es202212
    audio_dv
    audio_dvi4
    audio_eac3
    audio_encaprtp
    audio_evrc
    audio_evrc_qcp
    audio_evrc0
    audio_evrc1
    audio_evrcb
    audio_evrcb0
    audio_evrcb1
    audio_evrcnw
    audio_evrcnw0
    audio_evrcnw1
    audio_evrcwb
    audio_evrcwb0
    audio_evrcwb1
    audio_evs
    audio_example
    audio_flac
    audio_flexfec
    audio_fwdred
    audio_g711_0
    audio_g719
    audio_g7221
    audio_g722
    audio_g723
    audio_g726_16
    audio_g726_24
    audio_g726_32
    audio_g726_40
    audio_g728
    audio_g729
    audio_g7291
    audio_g729_d
    audio_g729_e
    audio_gsm
    audio_gsm_efr
    audio_gsm_hr_08
    audio_i_lbc
    audio_ip_mr_v2_5
    audio_l8
    audio_l16
    audio_l20
    audio_l24
    audio_lpc
    audio_matroska
    audio_melp
    audio_melp600
    audio_melp1200
    audio_melp2400
    audio_mhas
    audio_midi_clip
    audio_mobile_xmf
    audio_mpa
    audio_mp4
    audio_mp4_a_latm
    audio_mpa_robust
    audio_mpeg
    audio_mpeg4_generic
    audio_ogg
    audio_opus
    audio_parityfec
    audio_pcma
    audio_pcma_wb
    audio_pcmu
    audio_pcmu_wb
    audio_prs_sid
    audio_qcelp
    audio_raptorfec
    audio_red
    audio_rtp_enc_aescm128
    audio_rtploopback
    audio_rtp_midi
    audio_rtx
    audio_scip
    audio_smv
    audio_smv0
    audio_smv_qcp
    audio_sofa
    audio_soundfont
    audio_sp_midi
    audio_speex
    audio_t140c
    audio_t38
    audio_telephone_event
    audio_tetra_acelp
    audio_tetra_acelp_bb
    audio_tone
    audio_tsvcis
    audio_uemclip
    audio_ulpfec
    audio_usac
    audio_vdvi
    audio_vmr_wb
    audio_vnd_3gpp_iufp
    audio_vnd_4_sb
    audio_vnd_audiokoz
    audio_vnd_blockfact_facta
    audio_vnd_celp
    audio_vnd_cisco_nse
    audio_vnd_cmles_radio_events
    audio_vnd_cns_anp1
    audio_vnd_cns_inf1
    audio_vnd_dece_audio
    audio_vnd_digital_winds
    audio_vnd_dlna_adts
    audio_vnd_dolby_heaac_1
    audio_vnd_dolby_heaac_2
    audio_vnd_dolby_mlp
    audio_vnd_dolby_mps
    audio_vnd_dolby_pl2
    audio_vnd_dolby_pl2x
    audio_vnd_dolby_pl2z
    audio_vnd_dolby_pulse_1
    audio_vnd_dra
    audio_vnd_dts
    audio_vnd_dts_hd
    audio_vnd_dts_uhd
    audio_vnd_dvb_file
    audio_vnd_everad_plj
    audio_vnd_hns_audio
    audio_vnd_lucent_voice
    audio_vnd_ms_playready_media_pya
    audio_vnd_nokia_mobile_xmf
    audio_vnd_nortel_vbk
    audio_vnd_nuera_ecelp4800
    audio_vnd_nuera_ecelp7470
    audio_vnd_nuera_ecelp9600
    audio_vnd_octel_sbc
    audio_vnd_presonus_multitrack
    audio_vnd_qcelp
    audio_vnd_rhetorex_32kadpcm
    audio_vnd_rip
    audio_vnd_sealedmedia_softseal_mpeg
    audio_vnd_vmx_cvsd
    audio_vorbis
    audio_vorbis_config
    font_collection
    font_otf
    font_sfnt
    font_ttf
    font_woff
    font_woff2
    haptics_ivs
    haptics_hjif
    haptics_hmpg
    image_aces
    image_apng
    image_avci
    image_avcs
    image_avif
    image_bmp
    image_cgm
    image_dicom_rle
    image_dpx
    image_emf
    image_example
    image_fits
    image_g3fax
    image_gif
    image_heic
    image_heic_sequence
    image_heif
    image_heif_sequence
    image_hej2k
    image_hsj2
    image_ief
    image_j2c
    image_jaii
    image_jais
    image_jls
    image_jp2
    image_jpeg
    image_jph
    image_jphc
    image_jpm
    image_jpx
    image_jxl
    image_jxr
    image_jxr_a
    image_jxr_s
    image_jxs
    image_jxsc
    image_jxsi
    image_jxss
    image_ktx
    image_ktx2
    image_naplps
    image_png
    image_prs_btif
    image_prs_pti
    image_pwg_raster
    image_svg_xml
    image_t38
    image_tiff
    image_tiff_fx
    image_vnd_adobe_photoshop
    image_vnd_airzip_accelerator_azv
    image_vnd_blockfact_facti
    image_vnd_clip
    image_vnd_cns_inf2
    image_vnd_dece_graphic
    image_vnd_djvu
    image_vnd_dwg
    image_vnd_dxf
    image_vnd_dvb_subtitle
    image_vnd_fastbidsheet
    image_vnd_fpx
    image_vnd_fst
    image_vnd_fujixerox_edmics_mmr
    image_vnd_fujixerox_edmics_rlc
    image_vnd_globalgraphics_pgb
    image_vnd_microsoft_icon
    image_vnd_mix
    image_vnd_ms_modi
    image_vnd_mozilla_apng
    image_vnd_net_fpx
    image_vnd_pco_b16
    image_vnd_radiance
    image_vnd_sealed_png
    image_vnd_sealedmedia_softseal_gif
    image_vnd_sld
    image_vnd_sealedmedia_softseal_jpg
    image_vnd_svf
    image_vnd_tencent_tap
    image_vnd_valve_source_texture
    image_vnd_wap_wbmp
    image_vnd_xiff
    image_vnd_zbrush_pcx
    image_webp
    image_wmf
    image_x_emf
    image_x_wmf
    message_bhttp
    message_cpim
    message_delivery_status
    message_disposition_notification
    message_example
    message_external_body
    message_feedback_report
    message_global
    message_global_delivery_status
    message_global_disposition_notification
    message_global_headers
    message_http
    message_imdn_xml
    message_mls
    message_news
    message_ohttp_chunked_req
    message_ohttp_chunked_res
    message_ohttp_req
    message_ohttp_res
    message_partial
    message_rfc822
    message_s_http
    message_sip
    message_sipfrag
    message_tracking_status
    message_vnd_si_simp
    message_vnd_wfa_wsc
    model_3mf
    model_e57
    model_example
    model_gltf_binary
    model_gltf_json
    model_jt
    model_iges
    model_mesh
    model_mtl
    model_obj
    model_prc
    model_step
    model_step_xml
    model_step_zip
    model_step_xml_zip
    model_stl
    model_u3d
    model_vnd_bary
    model_vnd_cld
    model_vnd_collada_xml
    model_vnd_dwf
    model_vnd_flatland_3dml
    model_vnd_gdl
    model_vnd_gs_gdl
    model_vnd_gtw
    model_vnd_moml_xml
    model_vnd_mts
    model_vnd_opengex
    model_vnd_parasolid_transmit_binary
    model_vnd_parasolid_transmit_text
    model_vnd_pytha_pyox
    model_vnd_rosette_annotated_data_model
    model_vnd_sap_vds
    model_vnd_usda
    model_vnd_usdz_zip
    model_vnd_valve_source_compiled_map
    model_vnd_vtu
    model_vrml
    model_x3d_vrml
    model_x3d_fastinfoset
    model_x3d_xml
    multipart_alternative
    multipart_appledouble
    multipart_byteranges
    multipart_digest
    multipart_encrypted
    multipart_example
    multipart_form_data
    multipart_header_set
    multipart_mixed
    multipart_multilingual
    multipart_parallel
    multipart_related
    multipart_report
    multipart_signed
    multipart_vnd_bint_med_plus
    multipart_voice_message
    multipart_x_mixed_replace
    text_1d_interleaved_parityfec
    text_cache_manifest
    text_calendar
    text_cql
    text_cql_expression
    text_cql_identifier
    text_css
    text_csv
    text_csv_schema
    text_directory
    text_dns
    text_ecmascript
    text_encaprtp
    text_enriched
    text_example
    text_fhirpath
    text_flexfec
    text_fwdred
    text_gff3
    text_grammar_ref_list
    text_hl7v2
    text_html
    text_javascript
    text_jcr_cnd
    text_markdown
    text_mizar
    text_n3
    text_org
    text_parameters
    text_parityfec
    text_plain
    text_provenance_notation
    text_prs_fallenstein_rst
    text_prs_lines_tag
    text_prs_prop_logic
    text_prs_texi
    text_raptorfec
    text_red
    text_rfc822_headers
    text_richtext
    text_rtf
    text_rtp_enc_aescm128
    text_rtploopback
    text_rtx
    text_sgml
    text_shaclc
    text_shex
    text_spdx
    text_strings
    text_t140
    text_tab_separated_values
    text_troff
    text_turtle
    text_ulpfec
    text_uri_list
    text_vcard
    text_vnd_a
    text_vnd_abc
    text_vnd_ascii_art
    text_vnd_curl
    text_vnd_debian_copyright
    text_vnd_dm_client_script
    text_vnd_dvb_subtitle
    text_vnd_esmertec_theme_descriptor
    text_vnd_exchangeable
    text_vnd_familysearch_gedcom
    text_vnd_ficlab_flt
    text_vnd_fly
    text_vnd_fmi_flexstor
    text_vnd_gml
    text_vnd_graphviz
    text_vnd_hans
    text_vnd_hekaya
    text_vnd_hgl
    text_vnd_in3d_3dml
    text_vnd_in3d_spot
    text_vnd_iptc_news_ml
    text_vnd_iptc_nitf
    text_vnd_latex_z
    text_vnd_longform
    text_vnd_motorola_reflex
    text_vnd_ms_mediapackage
    text_vnd_net2phone_commcenter_command
    text_vnd_radisys_msml_basic_layout
    text_vnd_senx_warpscript
    text_vnd_si_uricatalogue
    text_vnd_sun_j2me_app_descriptor
    text_vnd_sosi
    text_vnd_tps
    text_vnd_typst
    text_vnd_trolltech_linguist
    text_vnd_vcf
    text_vnd_vri
    text_vnd_wap_si
    text_vnd_wap_sl
    text_vnd_wap_wml
    text_vnd_wap_wmlscript
    text_vnd_zoo_kcl
    text_vtt
    text_wgsl
    text_xml
    text_xml_external_parsed_entity
    video_1d_interleaved_parityfec
    video_3gpp
    video_3gpp2
    video_3gpp_tt
    video_av1
    video_bmpeg
    video_bt656
    video_cel_b
    video_dv
    video_encaprtp
    video_evc
    video_example
    video_ffv1
    video_flexfec
    video_h261
    video_h263
    video_h263_1998
    video_h263_2000
    video_h264
    video_h264_rcdo
    video_h264_svc
    video_h265
    video_h266
    video_iso_segment
    video_jpeg
    video_jpeg2000
    video_jpeg2000_scl
    video_jxsv
    video_lottie_json
    video_matroska
    video_matroska_3d
    video_mj2
    video_mp1_s
    video_mp2_p
    video_mp2_t
    video_mp4
    video_mp4_v_es
    video_mpv
    video_mpeg
    video_mpeg4_generic
    video_nv
    video_ogg
    video_parityfec
    video_pointer
    video_quicktime
    video_raptorfec
    video_raw
    video_rtp_enc_aescm128
    video_rtploopback
    video_rtx
    video_scip
    video_smpte291
    video_smpte292_m
    video_ulpfec
    video_vc1
    video_vc2
    video_vnd_blockfact_factv
    video_vnd_cctv
    video_vnd_dece_hd
    video_vnd_dece_mobile
    video_vnd_dece_mp4
    video_vnd_dece_pd
    video_vnd_dece_sd
    video_vnd_dece_video
    video_vnd_directv_mpeg
    video_vnd_directv_mpeg_tts
    video_vnd_dlna_mpeg_tts
    video_vnd_dvb_file
    video_vnd_fvt
    video_vnd_hns_video
    video_vnd_iptvforum_1dparityfec_1010
    video_vnd_iptvforum_1dparityfec_2005
    video_vnd_iptvforum_2dparityfec_1010
    video_vnd_iptvforum_2dparityfec_2005
    video_vnd_iptvforum_ttsavc
    video_vnd_iptvforum_ttsmpeg2
    video_vnd_motorola_video
    video_vnd_motorola_videop
    video_vnd_mpegurl
    video_vnd_ms_playready_media_pyv
    video_vnd_nokia_interleaved_multimedia
    video_vnd_nokia_mp4vr
    video_vnd_nokia_videovoip
    video_vnd_objectvideo
    video_vnd_planar
    video_vnd_radgamettools_bink
    video_vnd_radgamettools_smacker
    video_vnd_sealed_mpeg1
    video_vnd_sealed_mpeg4
    video_vnd_sealed_swf
    video_vnd_sealedmedia_softseal_mov
    video_vnd_uvvu_mp4
    video_vnd_youtube_yt
    video_vnd_vivo
    video_vp8
    video_vp9
}
